// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.6.0
// Generated from: nitro_http.native.dart
// NativeImpl: cpp — shared C++ virtual-dispatch bridge (no JNI / Swift).
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <string>
#include <stdexcept>
#include "dart_api_dl.h"
#include "nitro_http.bridge.g.h"
#include "nitro_http.native.g.h"

extern "C" {
NITRO_EXPORT uint32_t nitro_http_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_http_nitro_bridge_checksum(void) {
    return "f03160ce749c3a4a";
}
NITRO_EXPORT intptr_t nitro_http_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}

static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };
alignas(8) static thread_local uint8_t _g_opt_ret[16];
static thread_local std::string _g_str_ret;

extern "C" {
NitroError* nitro_http_get_error() { return &g_nitro_error; }
void nitro_http_clear_error() {
    if (!g_nitro_error.hasError) { return; }
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name)       { free((void*)g_nitro_error.name);       g_nitro_error.name       = nullptr; }
    if (g_nitro_error.message)    { free((void*)g_nitro_error.message);    g_nitro_error.message    = nullptr; }
    if (g_nitro_error.code)       { free((void*)g_nitro_error.code);       g_nitro_error.code       = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}
static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_http_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name       = name    ? strdup(name)    : strdup("NativeException");
    g_nitro_error.message    = message ? strdup(message) : strdup("An unknown C++ exception occurred.");
    g_nitro_error.code       = code    ? strdup(code)    : nullptr;
    g_nitro_error.stackTrace = stack   ? strdup(stack)   : nullptr;
}
}

#include <atomic>
#include <memory>
#include <mutex>
#include <unordered_map>

using HybridNitroHttpNativeFactory = std::function<std::shared_ptr<HybridNitroHttpNative>(const std::string&)>;
static std::unordered_map<int64_t, std::shared_ptr<HybridNitroHttpNative>>& _g_instances() {
    static std::unordered_map<int64_t, std::shared_ptr<HybridNitroHttpNative>> m;
    return m;
}
static std::mutex& _g_instances_mtx() {
    static std::mutex m;
    return m;
}
static std::atomic<int64_t>& _g_next_instance_id() {
    static std::atomic<int64_t> id{1};
    return id;
}
static HybridNitroHttpNativeFactory& _g_factory() {
    static HybridNitroHttpNativeFactory f;
    return f;
}

static constexpr int _kNitroCacheWays = 8;
struct alignas(64) _NitroInstSlot {
    std::atomic<int64_t> id{-1};
    std::atomic<HybridNitroHttpNative*> ptr{nullptr};
};
static _NitroInstSlot _g_inst_cache[_kNitroCacheWays];
static HybridNitroHttpNative* _nitro_get_instance(int64_t id) {
    _NitroInstSlot& _slot = _g_inst_cache[(uint64_t)id & (_kNitroCacheWays - 1)];
    if (_slot.id.load(std::memory_order_acquire) == id) {
        return _slot.ptr.load(std::memory_order_relaxed);
    }
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto it = _g_instances().find(id);
    HybridNitroHttpNative* p = (it != _g_instances().end()) ? it->second.get() : nullptr;
    if (p) {
        _slot.ptr.store(p, std::memory_order_relaxed);
        _slot.id.store(id, std::memory_order_release);
    }
    return p;
}
static void _nitro_invalidate_cache() {
    for (int _i = 0; _i < _kNitroCacheWays; ++_i) {
        _g_inst_cache[_i].id.store(-1, std::memory_order_release);
        _g_inst_cache[_i].ptr.store(nullptr, std::memory_order_relaxed);
    }
}

extern "C" {
void nitro_http_register_factory(void* fn) {
    _g_factory() = *static_cast<HybridNitroHttpNativeFactory*>(fn);
}
void nitro_http_register_impl(HybridNitroHttpNative* impl) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    if (impl) _g_instances()[0] = std::shared_ptr<HybridNitroHttpNative>(impl, [](HybridNitroHttpNative*){});
    else _g_instances().erase(0);
    _nitro_invalidate_cache();
}
HybridNitroHttpNative* nitro_http_get_impl() {
    return _nitro_get_instance(0);
}
NITRO_EXPORT int64_t nitro_http_create_instance(const char* key) {
    if (_g_factory()) {
        auto inst = _g_factory()(key ? key : "");
        if (!inst) return -1;
        std::lock_guard<std::mutex> _lk(_g_instances_mtx());
        int64_t id = ++_g_next_instance_id();
        _g_instances()[id] = std::move(inst);
        return id;
    }
    // Legacy: no factory registered — return 0 (single global impl slot)
    return 0;
}
NITRO_EXPORT void nitro_http_destroy_instance(int64_t instanceId) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    _g_instances().erase(instanceId);
    _nitro_invalidate_cache();
}
NITRO_EXPORT void nitro_http_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_http_nitro_alloc(size_t size) { return malloc(size); }
}

#include <algorithm>
#include <mutex>
#include <vector>

// One registry per stream: every concurrent Dart subscriber registers
// its own ReceivePort. Guarded by a mutex — register/release run on the
// Dart isolate thread while emits may come from any impl thread.
struct _NitroStreamPorts {
    std::mutex mtx;
    std::vector<int64_t> ports;
    void add(int64_t p) { std::lock_guard<std::mutex> l(mtx); ports.push_back(p); }
    void remove(int64_t p) { std::lock_guard<std::mutex> l(mtx); ports.erase(std::remove(ports.begin(), ports.end(), p), ports.end()); }
    std::vector<int64_t> snapshot() { std::lock_guard<std::mutex> l(mtx); return ports; }
};
static _NitroStreamPorts g_ports_chunks;
static _NitroStreamPorts g_ports_events;
static _NitroStreamPorts g_ports_wsFrames;

void HybridNitroHttpNative::emit_chunks(RawChunk item) {
    auto _ports = g_ports_chunks.snapshot();
    if (_ports.empty()) { return; }
    Dart_CObject obj;
    for (int64_t _port : _ports) {
        RawChunk* st_ptr = (RawChunk*)malloc(sizeof(RawChunk));
        if (!st_ptr) { break; }
        *st_ptr = item;
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)st_ptr;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(st_ptr);
            g_ports_chunks.remove(_port);
        }
    }
}

void HybridNitroHttpNative::emit_events(NitroCppBuffer item) {
    auto _ports = g_ports_events.snapshot();
    if (_ports.empty()) { if (item.data) { free((void*)item.data); } return; }
    Dart_CObject obj;
    if (item.data == nullptr) {
        obj.type = Dart_CObject_kNull;
        for (int64_t _port : _ports) {
            if (!Dart_PostCObject_DL(_port, &obj)) { g_ports_events.remove(_port); }
        }
        return;
    }
    for (int64_t _port : _ports) {
        uint8_t* _copy = (uint8_t*)malloc(item.size);
        if (!_copy) { break; }
        memcpy(_copy, item.data, item.size);
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)_copy;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(_copy);
            g_ports_events.remove(_port);
        }
    }
    free((void*)item.data);
}

void HybridNitroHttpNative::emit_wsFrames(RawWsFrame item) {
    auto _ports = g_ports_wsFrames.snapshot();
    if (_ports.empty()) { return; }
    Dart_CObject obj;
    for (int64_t _port : _ports) {
        RawWsFrame* st_ptr = (RawWsFrame*)malloc(sizeof(RawWsFrame));
        if (!st_ptr) { break; }
        *st_ptr = item;
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)st_ptr;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(st_ptr);
            g_ports_wsFrames.remove(_port);
        }
    }
}

// S8 helper — writes error info to the out-param slot.
static void _nitro_out_err(NitroError* e, const char* name, const char* msg) {
    if (!e) return;
    e->hasError = 1;
    e->name       = name ? strdup(name) : nullptr;
    e->message    = msg  ? strdup(msg)  : nullptr;
    e->code       = nullptr;
    e->stackTrace = nullptr;
}

extern "C" {

const char* nitro_http_engine_version(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return nullptr; }
    try {
        std::string _res = _impl->engineVersion();
        _g_str_ret = _res; return const_cast<char*>(_g_str_ret.c_str());
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

int8_t nitro_http_supports_http3(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return false; }
    try {
        return _impl->supportsHttp3();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

int8_t nitro_http_supports_web_sockets(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return false; }
    try {
        return _impl->supportsWebSockets();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

int8_t nitro_http_supports_brotli(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return false; }
    try {
        return _impl->supportsBrotli();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

int8_t nitro_http_supports_zstd(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return false; }
    try {
        return _impl->supportsZstd();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

void nitro_http_reset_native(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->resetNative();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_configure_client(int64_t instanceId, void* config, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_config = { (const uint8_t*)config + 4, (size_t)*(int32_t*)config };
        _impl->configureClient(_buf_config);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_send_buffered(int64_t instanceId, void* request, uint8_t* body, size_t body_length, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) {
        _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        _impl->sendBuffered(NitroCppBuffer{ (const uint8_t*)request + 4, (size_t)*(int32_t*)request }, body, static_cast<size_t>(body_length), _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

void nitro_http_send_buffered_coalesced(int64_t instanceId, int64_t callId, void* request, uint8_t* body, size_t body_length, int64_t dartPort, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_request = { (const uint8_t*)request + 4, (size_t)*(int32_t*)request };
        _impl->sendBufferedCoalesced(callId, _buf_request, body, static_cast<size_t>(body_length), dartPort);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_release_record(int64_t instanceId, int64_t address, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->releaseRecord(address);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_start_streamed(int64_t instanceId, void* request, uint8_t* body, size_t body_length, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) {
        _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        _impl->startStreamed(NitroCppBuffer{ (const uint8_t*)request + 4, (size_t)*(int32_t*)request }, body, static_cast<size_t>(body_length), _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

void nitro_http_cancel(int64_t instanceId, int64_t requestId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->cancel(requestId);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_cancel_all(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->cancelAll();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_cancel_token(int64_t instanceId, int64_t tokenId, const char* reason, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->cancelToken(tokenId, std::string(reason));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_release_cancel_token(int64_t instanceId, int64_t tokenId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->releaseCancelToken(tokenId);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_grant_credit(int64_t instanceId, int64_t requestId, int64_t chunkCount, int64_t ackedChunks, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->grantCredit(requestId, chunkCount, ackedChunks);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

int64_t nitro_http_feed_upload_chunk(int64_t instanceId, int64_t requestId, uint8_t* chunk, size_t chunk_length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return 0; }
    try {
        return _impl->feedUploadChunk(requestId, chunk, static_cast<size_t>(chunk_length));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_http_finish_upload(int64_t instanceId, int64_t requestId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->finishUpload(requestId);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_fail_upload(int64_t instanceId, int64_t requestId, const char* message, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->failUpload(requestId, std::string(message));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void* nitro_http_get_cookies(int64_t instanceId, const char* url, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->getCookies(std::string(url));
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void nitro_http_set_cookie(int64_t instanceId, void* cookie, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_cookie = { (const uint8_t*)cookie + 4, (size_t)*(int32_t*)cookie };
        _impl->setCookie(_buf_cookie);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_clear_cookies(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->clearCookies();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_flush_cookies(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->flushCookies();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_configure_cache(int64_t instanceId, void* config, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_config = { (const uint8_t*)config + 4, (size_t)*(int32_t*)config };
        _impl->configureCache(_buf_config);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_prefetch(int64_t instanceId, void* request, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) {
        _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        _impl->prefetch(NitroCppBuffer{ (const uint8_t*)request + 4, (size_t)*(int32_t*)request }, _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

void nitro_http_clear_cache(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->clearCache();
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void* nitro_http_cache_stats(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->cacheStats();
        return (uint8_t*)_res.data;
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void nitro_http_ws_connect(int64_t instanceId, void* config, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) {
        _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        _impl->wsConnect(NitroCppBuffer{ (const uint8_t*)config + 4, (size_t)*(int32_t*)config }, _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

int64_t nitro_http_ws_send(int64_t instanceId, int64_t opcode, uint8_t* payload, size_t payload_length, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return 0; }
    try {
        return _impl->wsSend(opcode, payload, static_cast<size_t>(payload_length));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_http_ws_close(int64_t instanceId, int64_t code, const char* reason, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->wsClose(code, std::string(reason));
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_ws_grant_credit(int64_t instanceId, int64_t frameCount, int64_t ackedFrames, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_http_register_factory() or nitro_http_register_impl()."); return; }
    try {
        _impl->wsGrantCredit(frameCount, ackedFrames);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_http_register_chunks_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_chunks.add(dart_port);
}
void nitro_http_release_chunks_stream(int64_t dart_port) {
    g_ports_chunks.remove(dart_port);
}

void nitro_http_register_events_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_events.add(dart_port);
}
void nitro_http_release_events_stream(int64_t dart_port) {
    g_ports_events.remove(dart_port);
}

void nitro_http_register_ws_frames_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_wsFrames.add(dart_port);
}
void nitro_http_release_ws_frames_stream(int64_t dart_port) {
    g_ports_wsFrames.remove(dart_port);
}

// Frees a malloc'd [RawChunk] wrapper allocated by the stream emitter.
// Called automatically by NativeFinalizer when the Dart proxy is GC'd.
void nitro_http_release_RawChunk(void* ptr) {
    if (!ptr) { return; }
    free(ptr);
}

// Frees a malloc'd [RawWsFrame] wrapper allocated by the stream emitter.
// Called automatically by NativeFinalizer when the Dart proxy is GC'd.
void nitro_http_release_RawWsFrame(void* ptr) {
    if (!ptr) { return; }
    free(ptr);
}

} // extern "C"
