// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.4
// Generated from: nitro_http.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_http.native.dart';

// Web-split layout (this spec targets web): this part holds only the
// platform-neutral codecs. The dart:ffi implementation lives in
// generated/native/nitro_http.ffi.g.dart; construct instances via the
// conditional factory in nitro_http.platform.g.dart.

// --- Enum FFI helpers (generated by Nitrogen) ---

extension RawMethodNativeExt on RawMethod {
  int get nativeValue => index + 0;
}

extension RawMethodFromNativeExt on int {
  RawMethod toRawMethod() => RawMethod.values[this - 0];
}

extension RawHttpVersionPrefNativeExt on RawHttpVersionPref {
  int get nativeValue => index + 0;
}

extension RawHttpVersionPrefFromNativeExt on int {
  RawHttpVersionPref toRawHttpVersionPref() =>
      RawHttpVersionPref.values[this - 0];
}

extension RawHttpVersionNativeExt on RawHttpVersion {
  int get nativeValue => index + 0;
}

extension RawHttpVersionFromNativeExt on int {
  RawHttpVersion toRawHttpVersion() => RawHttpVersion.values[this - 0];
}

extension RawErrorKindNativeExt on RawErrorKind {
  int get nativeValue => index + 0;
}

extension RawErrorKindFromNativeExt on int {
  RawErrorKind toRawErrorKind() => RawErrorKind.values[this - 0];
}

extension RawProxyModeNativeExt on RawProxyMode {
  int get nativeValue => index + 0;
}

extension RawProxyModeFromNativeExt on int {
  RawProxyMode toRawProxyMode() => RawProxyMode.values[this - 0];
}

extension RawCacheModeNativeExt on RawCacheMode {
  int get nativeValue => index + 0;
}

extension RawCacheModeFromNativeExt on int {
  RawCacheMode toRawCacheMode() => RawCacheMode.values[this - 0];
}

extension RawBodyKindNativeExt on RawBodyKind {
  int get nativeValue => index + 0;
}

extension RawBodyKindFromNativeExt on int {
  RawBodyKind toRawBodyKind() => RawBodyKind.values[this - 0];
}

extension RawChunkKindNativeExt on RawChunkKind {
  int get nativeValue => index + 0;
}

extension RawChunkKindFromNativeExt on int {
  RawChunkKind toRawChunkKind() => RawChunkKind.values[this - 0];
}

extension RawEventKindNativeExt on RawEventKind {
  int get nativeValue => index + 0;
}

extension RawEventKindFromNativeExt on int {
  RawEventKind toRawEventKind() => RawEventKind.values[this - 0];
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension RawHeaderRecordExt on RawHeader {
  static RawHeader fromReader(RecordReaderBase r) =>
      RawHeader(name: r.readString(), value: r.readString());

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeString(value);
  }
}

extension RawTlsConfigRecordExt on RawTlsConfig {
  static RawTlsConfig fromReader(RecordReaderBase r) => RawTlsConfig(
    verifyCertificates: r.readBool(),
    rootCaSource: r.readInt(),
    trustedRootsPem: r.readString(),
    clientCertPem: r.readString(),
    clientKeyPem: r.readString(),
    clientKeyPassword: r.readString(),
    pinnedSpkiSha256: List.generate(r.readInt32(), (_) => r.readString()),
    minTlsVersion: r.readInt(),
    maxTlsVersion: r.readInt(),
    sniHostname: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(verifyCertificates);
    writer.writeInt(rootCaSource);
    writer.writeString(trustedRootsPem);
    writer.writeString(clientCertPem);
    writer.writeString(clientKeyPem);
    writer.writeString(clientKeyPassword);
    writer.writeInt32(pinnedSpkiSha256.length);
    for (final e in pinnedSpkiSha256) {
      writer.writeString(e);
    }
    writer.writeInt(minTlsVersion);
    writer.writeInt(maxTlsVersion);
    writer.writeString(sniHostname);
  }
}

extension RawProxyConfigRecordExt on RawProxyConfig {
  static RawProxyConfig fromReader(RecordReaderBase r) => RawProxyConfig(
    mode: r.readInt().toRawProxyMode(),
    url: r.readString(),
    username: r.readString(),
    password: r.readString(),
    noProxyHosts: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(mode.nativeValue);
    writer.writeString(url);
    writer.writeString(username);
    writer.writeString(password);
    writer.writeString(noProxyHosts);
  }
}

extension RawDnsConfigRecordExt on RawDnsConfig {
  static RawDnsConfig fromReader(RecordReaderBase r) => RawDnsConfig(
    staticOverrides: List.generate(r.readInt32(), (_) => r.readString()),
    dohUrl: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt32(staticOverrides.length);
    for (final e in staticOverrides) {
      writer.writeString(e);
    }
    writer.writeString(dohUrl);
  }
}

extension RawCookieConfigRecordExt on RawCookieConfig {
  static RawCookieConfig fromReader(RecordReaderBase r) =>
      RawCookieConfig(enabled: r.readBool(), persistPath: r.readString());

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(enabled);
    writer.writeString(persistPath);
  }
}

extension RawPoolConfigRecordExt on RawPoolConfig {
  static RawPoolConfig fromReader(RecordReaderBase r) => RawPoolConfig(
    maxConnections: r.readInt(),
    maxConnectionsPerHost: r.readInt(),
    idleTimeoutMs: r.readInt(),
    maxLifetimeMs: r.readInt(),
    keepAlivePingMs: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(maxConnections);
    writer.writeInt(maxConnectionsPerHost);
    writer.writeInt(idleTimeoutMs);
    writer.writeInt(maxLifetimeMs);
    writer.writeInt(keepAlivePingMs);
  }
}

extension RawClientConfigRecordExt on RawClientConfig {
  static RawClientConfig fromReader(RecordReaderBase r) => RawClientConfig(
    httpVersion: r.readInt().toRawHttpVersionPref(),
    connectTimeoutMs: r.readInt(),
    requestTimeoutMs: r.readInt(),
    idleTimeoutMs: r.readInt(),
    followRedirects: r.readBool(),
    maxRedirects: r.readInt(),
    enableCompression: r.readBool(),
    enableCache: r.readBool(),
    userAgent: r.readString(),
    altSvcCachePath: r.readString(),
    streamChunkBytes: r.readInt(),
    streamChunkMinContentLength: r.readInt(),
    streamChunkMaxHoldMs: r.readInt(),
    maxResponseBytes: r.readInt(),
    hstsCachePath: r.readString(),
    unixSocketPath: r.readString(),
    networkInterface: r.readString(),
    defaultHeaders: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    tls: RawTlsConfigRecordExt.fromReader(r),
    proxy: RawProxyConfigRecordExt.fromReader(r),
    dns: RawDnsConfigRecordExt.fromReader(r),
    cookies: RawCookieConfigRecordExt.fromReader(r),
    pool: RawPoolConfigRecordExt.fromReader(r),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(httpVersion.nativeValue);
    writer.writeInt(connectTimeoutMs);
    writer.writeInt(requestTimeoutMs);
    writer.writeInt(idleTimeoutMs);
    writer.writeBool(followRedirects);
    writer.writeInt(maxRedirects);
    writer.writeBool(enableCompression);
    writer.writeBool(enableCache);
    writer.writeString(userAgent);
    writer.writeString(altSvcCachePath);
    writer.writeInt(streamChunkBytes);
    writer.writeInt(streamChunkMinContentLength);
    writer.writeInt(streamChunkMaxHoldMs);
    writer.writeInt(maxResponseBytes);
    writer.writeString(hstsCachePath);
    writer.writeString(unixSocketPath);
    writer.writeString(networkInterface);
    writer.writeInt32(defaultHeaders.length);
    for (final e in defaultHeaders) {
      e.writeFields(writer);
    }
    tls.writeFields(writer);
    proxy.writeFields(writer);
    dns.writeFields(writer);
    cookies.writeFields(writer);
    pool.writeFields(writer);
  }
}

extension RawRequestOptionsRecordExt on RawRequestOptions {
  static RawRequestOptions fromReader(RecordReaderBase r) => RawRequestOptions(
    connectTimeoutMs: r.readInt(),
    requestTimeoutMs: r.readInt(),
    followRedirects: r.readInt(),
    maxRedirects: r.readInt(),
    cacheMode: r.readInt().toRawCacheMode(),
    reportProgress: r.readBool(),
    wantTimings: r.readBool(),
    uploadContentLength: r.readInt(),
    pinnedSpkiOverride: r.readString(),
    cancelTokenId: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(connectTimeoutMs);
    writer.writeInt(requestTimeoutMs);
    writer.writeInt(followRedirects);
    writer.writeInt(maxRedirects);
    writer.writeInt(cacheMode.nativeValue);
    writer.writeBool(reportProgress);
    writer.writeBool(wantTimings);
    writer.writeInt(uploadContentLength);
    writer.writeString(pinnedSpkiOverride);
    writer.writeInt(cancelTokenId);
  }
}

extension RawRequestRecordExt on RawRequest {
  static RawRequest fromReader(RecordReaderBase r) => RawRequest(
    requestId: r.readInt(),
    method: r.readInt().toRawMethod(),
    customMethod: r.readString(),
    url: r.readString(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    bodyKind: r.readInt().toRawBodyKind(),
    bodyFilePath: r.readString(),
    responseFilePath: r.readString(),
    options: RawRequestOptionsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(requestId);
    writer.writeInt(method.nativeValue);
    writer.writeString(customMethod);
    writer.writeString(url);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeInt(bodyKind.nativeValue);
    writer.writeString(bodyFilePath);
    writer.writeString(responseFilePath);
    options.writeFields(writer);
  }
}

extension RawTimingsRecordExt on RawTimings {
  static RawTimings fromReader(RecordReaderBase r) => RawTimings(
    queueMs: r.readDouble(),
    dnsMs: r.readDouble(),
    connectMs: r.readDouble(),
    tlsMs: r.readDouble(),
    firstByteMs: r.readDouble(),
    redirectMs: r.readDouble(),
    totalMs: r.readDouble(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeDouble(queueMs);
    writer.writeDouble(dnsMs);
    writer.writeDouble(connectMs);
    writer.writeDouble(tlsMs);
    writer.writeDouble(firstByteMs);
    writer.writeDouble(redirectMs);
    writer.writeDouble(totalMs);
  }
}

extension RawResponseRecordExt on RawResponse {
  static RawResponse fromReader(RecordReaderBase r) => RawResponse(
    requestId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    reasonPhrase: r.readString(),
    version: r.readInt().toRawHttpVersion(),
    finalUrl: r.readString(),
    redirectCount: r.readInt(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    body: r.readBlob(),
    fromCache: r.readBool(),
    revalidated: r.readBool(),
    primaryIp: r.readString(),
    primaryPort: r.readInt(),
    timings: RawTimingsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(requestId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(reasonPhrase);
    writer.writeInt(version.nativeValue);
    writer.writeString(finalUrl);
    writer.writeInt(redirectCount);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeBlob(body);
    writer.writeBool(fromCache);
    writer.writeBool(revalidated);
    writer.writeString(primaryIp);
    writer.writeInt(primaryPort);
    timings.writeFields(writer);
  }
}

extension RawResponseHeadRecordExt on RawResponseHead {
  static RawResponseHead fromReader(RecordReaderBase r) => RawResponseHead(
    requestId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    reasonPhrase: r.readString(),
    version: r.readInt().toRawHttpVersion(),
    finalUrl: r.readString(),
    redirectCount: r.readInt(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    fromCache: r.readBool(),
    contentLength: r.readInt(),
    primaryIp: r.readString(),
    primaryPort: r.readInt(),
    timings: RawTimingsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(requestId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(reasonPhrase);
    writer.writeInt(version.nativeValue);
    writer.writeString(finalUrl);
    writer.writeInt(redirectCount);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeBool(fromCache);
    writer.writeInt(contentLength);
    writer.writeString(primaryIp);
    writer.writeInt(primaryPort);
    timings.writeFields(writer);
  }
}

extension RawEventRecordExt on RawEvent {
  static RawEvent fromReader(RecordReaderBase r) => RawEvent(
    requestId: r.readInt(),
    kind: r.readInt().toRawEventKind(),
    a: r.readInt(),
    b: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(requestId);
    writer.writeInt(kind.nativeValue);
    writer.writeInt(a);
    writer.writeInt(b);
    writer.writeString(message);
  }
}

extension RawCookieRecordExt on RawCookie {
  static RawCookie fromReader(RecordReaderBase r) => RawCookie(
    name: r.readString(),
    value: r.readString(),
    domain: r.readString(),
    path: r.readString(),
    expiresEpochMs: r.readInt(),
    secure: r.readBool(),
    httpOnly: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeString(value);
    writer.writeString(domain);
    writer.writeString(path);
    writer.writeInt(expiresEpochMs);
    writer.writeBool(secure);
    writer.writeBool(httpOnly);
  }
}

extension RawCacheConfigRecordExt on RawCacheConfig {
  static RawCacheConfig fromReader(RecordReaderBase r) => RawCacheConfig(
    enabled: r.readBool(),
    directory: r.readString(),
    maxSizeBytes: r.readInt(),
    maxEntryBytes: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(enabled);
    writer.writeString(directory);
    writer.writeInt(maxSizeBytes);
    writer.writeInt(maxEntryBytes);
  }
}

extension RawCacheStatsRecordExt on RawCacheStats {
  static RawCacheStats fromReader(RecordReaderBase r) => RawCacheStats(
    entryCount: r.readInt(),
    sizeBytes: r.readInt(),
    hitCount: r.readInt(),
    missCount: r.readInt(),
    revalidationCount: r.readInt(),
    evictionCount: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(entryCount);
    writer.writeInt(sizeBytes);
    writer.writeInt(hitCount);
    writer.writeInt(missCount);
    writer.writeInt(revalidationCount);
    writer.writeInt(evictionCount);
  }
}

extension RawWsConfigRecordExt on RawWsConfig {
  static RawWsConfig fromReader(RecordReaderBase r) => RawWsConfig(
    socketId: r.readInt(),
    url: r.readString(),
    protocols: List.generate(r.readInt32(), (_) => r.readString()),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    pingIntervalMs: r.readInt(),
    maxFrameBytes: r.readInt(),
    connectTimeoutMs: r.readInt(),
    tls: RawTlsConfigRecordExt.fromReader(r),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(socketId);
    writer.writeString(url);
    writer.writeInt32(protocols.length);
    for (final e in protocols) {
      writer.writeString(e);
    }
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeInt(pingIntervalMs);
    writer.writeInt(maxFrameBytes);
    writer.writeInt(connectTimeoutMs);
    tls.writeFields(writer);
  }
}

extension RawWsHandshakeRecordExt on RawWsHandshake {
  static RawWsHandshake fromReader(RecordReaderBase r) => RawWsHandshake(
    socketId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    negotiatedProtocol: r.readString(),
    responseHeaders: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(socketId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(negotiatedProtocol);
    writer.writeInt32(responseHeaders.length);
    for (final e in responseHeaders) {
      e.writeFields(writer);
    }
  }
}
