// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.4
// Generated from: nitro_http.native.dart
/// Platform-conditional factory for [NitroHttpNative]:
///
/// ```dart
/// import 'nitro_http.platform.g.dart';
///
/// await ensureNitroHttpNativeReady();               // no-op on native
/// final api = createNitroHttpNativeInstance();
/// ```
library;

export 'generated/native/nitro_http.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_http.web.bridge.g.dart'
    show createNitroHttpNativeInstance, ensureNitroHttpNativeReady;
