// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.6.1
// Generated from: nitro_http.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_http.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension RawMethodNativeExt on RawMethod {
  int get nativeValue => index + 0;
}

extension RawMethodFromNativeExt on int {
  RawMethod toRawMethod() => RawMethod.values[this - 0];
}

extension RawHttpVersionPrefNativeExt on RawHttpVersionPref {
  int get nativeValue => index + 0;
}

extension RawHttpVersionPrefFromNativeExt on int {
  RawHttpVersionPref toRawHttpVersionPref() =>
      RawHttpVersionPref.values[this - 0];
}

extension RawHttpVersionNativeExt on RawHttpVersion {
  int get nativeValue => index + 0;
}

extension RawHttpVersionFromNativeExt on int {
  RawHttpVersion toRawHttpVersion() => RawHttpVersion.values[this - 0];
}

extension RawErrorKindNativeExt on RawErrorKind {
  int get nativeValue => index + 0;
}

extension RawErrorKindFromNativeExt on int {
  RawErrorKind toRawErrorKind() => RawErrorKind.values[this - 0];
}

extension RawProxyModeNativeExt on RawProxyMode {
  int get nativeValue => index + 0;
}

extension RawProxyModeFromNativeExt on int {
  RawProxyMode toRawProxyMode() => RawProxyMode.values[this - 0];
}

extension RawCacheModeNativeExt on RawCacheMode {
  int get nativeValue => index + 0;
}

extension RawCacheModeFromNativeExt on int {
  RawCacheMode toRawCacheMode() => RawCacheMode.values[this - 0];
}

extension RawBodyKindNativeExt on RawBodyKind {
  int get nativeValue => index + 0;
}

extension RawBodyKindFromNativeExt on int {
  RawBodyKind toRawBodyKind() => RawBodyKind.values[this - 0];
}

extension RawChunkKindNativeExt on RawChunkKind {
  int get nativeValue => index + 0;
}

extension RawChunkKindFromNativeExt on int {
  RawChunkKind toRawChunkKind() => RawChunkKind.values[this - 0];
}

extension RawEventKindNativeExt on RawEventKind {
  int get nativeValue => index + 0;
}

extension RawEventKindFromNativeExt on int {
  RawEventKind toRawEventKind() => RawEventKind.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class RawChunkFfi extends Struct {
  external Pointer<Uint8> bytes;
  @Int64()
  external int bytesLength;
  @Int64()
  external int requestId;
  @Int64()
  external int kind;
  @Int64()
  external int aux;
}

extension RawChunkFfiExt on RawChunkFfi {
  RawChunk toDart() {
    return RawChunk(
      bytes: Uint8List.fromList(bytes.asTypedList(bytesLength)),
      requestId: requestId,
      kind: kind,
      aux: aux,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  ///
  /// [nativeFree] must be the free function matching the allocator that
  /// produced the fields — for native-returned structs, the module's
  /// `_nitroFree` (the exported C-runtime free). package:ffi's malloc.free
  /// is CoTaskMemFree on Windows and corrupts the heap on these pointers.
  void freeFields(void Function(Pointer<NativeType>) nativeFree) {}
}

extension RawChunkExt on RawChunk {
  Pointer<RawChunkFfi> toNative(Arena arena) {
    final ptr = arena<RawChunkFfi>();
    ptr.ref.bytes = bytes.toPointer(arena);
    ptr.ref.bytesLength = bytes.length;
    ptr.ref.requestId = requestId;
    ptr.ref.kind = kind;
    ptr.ref.aux = aux;
    return ptr;
  }
}

final class RawWsFrameFfi extends Struct {
  external Pointer<Uint8> payload;
  @Int64()
  external int payloadLength;
  @Int64()
  external int socketId;
  @Int64()
  external int opcode;
  @Int64()
  external int flags;
}

extension RawWsFrameFfiExt on RawWsFrameFfi {
  RawWsFrame toDart() {
    return RawWsFrame(
      payload: Uint8List.fromList(payload.asTypedList(payloadLength)),
      socketId: socketId,
      opcode: opcode,
      flags: flags,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  ///
  /// [nativeFree] must be the free function matching the allocator that
  /// produced the fields — for native-returned structs, the module's
  /// `_nitroFree` (the exported C-runtime free). package:ffi's malloc.free
  /// is CoTaskMemFree on Windows and corrupts the heap on these pointers.
  void freeFields(void Function(Pointer<NativeType>) nativeFree) {}
}

extension RawWsFrameExt on RawWsFrame {
  Pointer<RawWsFrameFfi> toNative(Arena arena) {
    final ptr = arena<RawWsFrameFfi>();
    ptr.ref.payload = payload.toPointer(arena);
    ptr.ref.payloadLength = payload.length;
    ptr.ref.socketId = socketId;
    ptr.ref.opcode = opcode;
    ptr.ref.flags = flags;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [RawChunk].
/// Extends [RawChunk] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `RawChunkProxy <: RawChunk`, a `Stream<RawChunkProxy>`
/// satisfies `Stream<RawChunk>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_http_release_RawChunk'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class RawChunkProxy extends RawChunk implements Finalizable {
  final Pointer<RawChunkFfi> _native;

  static NativeFinalizer? _finalizer;
  static void Function(Pointer<Void>)? _releaseFn;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_http_release_RawChunk',
      ),
    );
    _releaseFn ??= dylib
        .lookupFunction<
          Void Function(Pointer<Void>),
          void Function(Pointer<Void>)
        >('nitro_http_release_RawChunk');
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  RawChunkProxy(this._native)
    : super(bytes: Uint8List(0), requestId: 0, kind: 0, aux: 0) {
    assert(
      _finalizer != null,
      'RawChunkProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get bytes => _native.ref.bytes.asTypedList(_native.ref.bytesLength);
  @override
  int get requestId => _native.ref.requestId;
  @override
  int get kind => _native.ref.kind;
  @override
  int get aux => _native.ref.aux;

  /// Eagerly copies all fields to a plain [RawChunk] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  RawChunk toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    _releaseFn!(_native.cast());
    return v;
  }
}

/// Zero-copy proxy for [RawWsFrame].
/// Extends [RawWsFrame] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `RawWsFrameProxy <: RawWsFrame`, a `Stream<RawWsFrameProxy>`
/// satisfies `Stream<RawWsFrame>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_http_release_RawWsFrame'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class RawWsFrameProxy extends RawWsFrame implements Finalizable {
  final Pointer<RawWsFrameFfi> _native;

  static NativeFinalizer? _finalizer;
  static void Function(Pointer<Void>)? _releaseFn;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_http_release_RawWsFrame',
      ),
    );
    _releaseFn ??= dylib
        .lookupFunction<
          Void Function(Pointer<Void>),
          void Function(Pointer<Void>)
        >('nitro_http_release_RawWsFrame');
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  RawWsFrameProxy(this._native)
    : super(payload: Uint8List(0), socketId: 0, opcode: 0, flags: 0) {
    assert(
      _finalizer != null,
      'RawWsFrameProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this, externalSize: 512);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get payload =>
      _native.ref.payload.asTypedList(_native.ref.payloadLength);
  @override
  int get socketId => _native.ref.socketId;
  @override
  int get opcode => _native.ref.opcode;
  @override
  int get flags => _native.ref.flags;

  /// Eagerly copies all fields to a plain [RawWsFrame] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  RawWsFrame toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    _releaseFn!(_native.cast());
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension RawHeaderRecordExt on RawHeader {
  static RawHeader fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawHeader fromReader(RecordReader r) =>
      RawHeader(name: r.readString(), value: r.readString());

  void writeFields(RecordWriter writer) {
    writer.writeString(name);
    writer.writeString(value);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawTlsConfigRecordExt on RawTlsConfig {
  static RawTlsConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawTlsConfig fromReader(RecordReader r) => RawTlsConfig(
    verifyCertificates: r.readBool(),
    rootCaSource: r.readInt(),
    trustedRootsPem: r.readString(),
    clientCertPem: r.readString(),
    clientKeyPem: r.readString(),
    clientKeyPassword: r.readString(),
    pinnedSpkiSha256: List.generate(r.readInt32(), (_) => r.readString()),
    minTlsVersion: r.readInt(),
    maxTlsVersion: r.readInt(),
    sniHostname: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeBool(verifyCertificates);
    writer.writeInt(rootCaSource);
    writer.writeString(trustedRootsPem);
    writer.writeString(clientCertPem);
    writer.writeString(clientKeyPem);
    writer.writeString(clientKeyPassword);
    writer.writeInt32(pinnedSpkiSha256.length);
    for (final e in pinnedSpkiSha256) {
      writer.writeString(e);
    }
    writer.writeInt(minTlsVersion);
    writer.writeInt(maxTlsVersion);
    writer.writeString(sniHostname);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawProxyConfigRecordExt on RawProxyConfig {
  static RawProxyConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawProxyConfig fromReader(RecordReader r) => RawProxyConfig(
    mode: r.readInt().toRawProxyMode(),
    url: r.readString(),
    username: r.readString(),
    password: r.readString(),
    noProxyHosts: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(mode.nativeValue);
    writer.writeString(url);
    writer.writeString(username);
    writer.writeString(password);
    writer.writeString(noProxyHosts);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawDnsConfigRecordExt on RawDnsConfig {
  static RawDnsConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawDnsConfig fromReader(RecordReader r) => RawDnsConfig(
    staticOverrides: List.generate(r.readInt32(), (_) => r.readString()),
    dohUrl: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt32(staticOverrides.length);
    for (final e in staticOverrides) {
      writer.writeString(e);
    }
    writer.writeString(dohUrl);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawCookieConfigRecordExt on RawCookieConfig {
  static RawCookieConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawCookieConfig fromReader(RecordReader r) =>
      RawCookieConfig(enabled: r.readBool(), persistPath: r.readString());

  void writeFields(RecordWriter writer) {
    writer.writeBool(enabled);
    writer.writeString(persistPath);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawPoolConfigRecordExt on RawPoolConfig {
  static RawPoolConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawPoolConfig fromReader(RecordReader r) => RawPoolConfig(
    maxConnections: r.readInt(),
    maxConnectionsPerHost: r.readInt(),
    idleTimeoutMs: r.readInt(),
    maxLifetimeMs: r.readInt(),
    keepAlivePingMs: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(maxConnections);
    writer.writeInt(maxConnectionsPerHost);
    writer.writeInt(idleTimeoutMs);
    writer.writeInt(maxLifetimeMs);
    writer.writeInt(keepAlivePingMs);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawClientConfigRecordExt on RawClientConfig {
  static RawClientConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawClientConfig fromReader(RecordReader r) => RawClientConfig(
    httpVersion: r.readInt().toRawHttpVersionPref(),
    connectTimeoutMs: r.readInt(),
    requestTimeoutMs: r.readInt(),
    idleTimeoutMs: r.readInt(),
    followRedirects: r.readBool(),
    maxRedirects: r.readInt(),
    enableCompression: r.readBool(),
    enableCache: r.readBool(),
    userAgent: r.readString(),
    altSvcCachePath: r.readString(),
    streamChunkBytes: r.readInt(),
    streamChunkMinContentLength: r.readInt(),
    streamChunkMaxHoldMs: r.readInt(),
    defaultHeaders: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    tls: RawTlsConfigRecordExt.fromReader(r),
    proxy: RawProxyConfigRecordExt.fromReader(r),
    dns: RawDnsConfigRecordExt.fromReader(r),
    cookies: RawCookieConfigRecordExt.fromReader(r),
    pool: RawPoolConfigRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(httpVersion.nativeValue);
    writer.writeInt(connectTimeoutMs);
    writer.writeInt(requestTimeoutMs);
    writer.writeInt(idleTimeoutMs);
    writer.writeBool(followRedirects);
    writer.writeInt(maxRedirects);
    writer.writeBool(enableCompression);
    writer.writeBool(enableCache);
    writer.writeString(userAgent);
    writer.writeString(altSvcCachePath);
    writer.writeInt(streamChunkBytes);
    writer.writeInt(streamChunkMinContentLength);
    writer.writeInt(streamChunkMaxHoldMs);
    writer.writeInt32(defaultHeaders.length);
    for (final e in defaultHeaders) {
      e.writeFields(writer);
    }
    tls.writeFields(writer);
    proxy.writeFields(writer);
    dns.writeFields(writer);
    cookies.writeFields(writer);
    pool.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawRequestOptionsRecordExt on RawRequestOptions {
  static RawRequestOptions fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawRequestOptions fromReader(RecordReader r) => RawRequestOptions(
    connectTimeoutMs: r.readInt(),
    requestTimeoutMs: r.readInt(),
    followRedirects: r.readInt(),
    maxRedirects: r.readInt(),
    cacheMode: r.readInt().toRawCacheMode(),
    reportProgress: r.readBool(),
    wantTimings: r.readBool(),
    uploadContentLength: r.readInt(),
    pinnedSpkiOverride: r.readString(),
    cancelTokenId: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(connectTimeoutMs);
    writer.writeInt(requestTimeoutMs);
    writer.writeInt(followRedirects);
    writer.writeInt(maxRedirects);
    writer.writeInt(cacheMode.nativeValue);
    writer.writeBool(reportProgress);
    writer.writeBool(wantTimings);
    writer.writeInt(uploadContentLength);
    writer.writeString(pinnedSpkiOverride);
    writer.writeInt(cancelTokenId);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawRequestRecordExt on RawRequest {
  static RawRequest fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawRequest fromReader(RecordReader r) => RawRequest(
    requestId: r.readInt(),
    method: r.readInt().toRawMethod(),
    customMethod: r.readString(),
    url: r.readString(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    bodyKind: r.readInt().toRawBodyKind(),
    bodyFilePath: r.readString(),
    options: RawRequestOptionsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(requestId);
    writer.writeInt(method.nativeValue);
    writer.writeString(customMethod);
    writer.writeString(url);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeInt(bodyKind.nativeValue);
    writer.writeString(bodyFilePath);
    options.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawTimingsRecordExt on RawTimings {
  static RawTimings fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawTimings fromReader(RecordReader r) => RawTimings(
    queueMs: r.readDouble(),
    dnsMs: r.readDouble(),
    connectMs: r.readDouble(),
    tlsMs: r.readDouble(),
    firstByteMs: r.readDouble(),
    redirectMs: r.readDouble(),
    totalMs: r.readDouble(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeDouble(queueMs);
    writer.writeDouble(dnsMs);
    writer.writeDouble(connectMs);
    writer.writeDouble(tlsMs);
    writer.writeDouble(firstByteMs);
    writer.writeDouble(redirectMs);
    writer.writeDouble(totalMs);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawResponseRecordExt on RawResponse {
  static RawResponse fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawResponse fromReader(RecordReader r) => RawResponse(
    requestId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    reasonPhrase: r.readString(),
    version: r.readInt().toRawHttpVersion(),
    finalUrl: r.readString(),
    redirectCount: r.readInt(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    body: r.readBlob(),
    fromCache: r.readBool(),
    revalidated: r.readBool(),
    primaryIp: r.readString(),
    primaryPort: r.readInt(),
    timings: RawTimingsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(requestId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(reasonPhrase);
    writer.writeInt(version.nativeValue);
    writer.writeString(finalUrl);
    writer.writeInt(redirectCount);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeBlob(body);
    writer.writeBool(fromCache);
    writer.writeBool(revalidated);
    writer.writeString(primaryIp);
    writer.writeInt(primaryPort);
    timings.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawResponseHeadRecordExt on RawResponseHead {
  static RawResponseHead fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawResponseHead fromReader(RecordReader r) => RawResponseHead(
    requestId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    reasonPhrase: r.readString(),
    version: r.readInt().toRawHttpVersion(),
    finalUrl: r.readString(),
    redirectCount: r.readInt(),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    fromCache: r.readBool(),
    contentLength: r.readInt(),
    primaryIp: r.readString(),
    primaryPort: r.readInt(),
    timings: RawTimingsRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(requestId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(reasonPhrase);
    writer.writeInt(version.nativeValue);
    writer.writeString(finalUrl);
    writer.writeInt(redirectCount);
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeBool(fromCache);
    writer.writeInt(contentLength);
    writer.writeString(primaryIp);
    writer.writeInt(primaryPort);
    timings.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawEventRecordExt on RawEvent {
  static RawEvent fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawEvent fromReader(RecordReader r) => RawEvent(
    requestId: r.readInt(),
    kind: r.readInt().toRawEventKind(),
    a: r.readInt(),
    b: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(requestId);
    writer.writeInt(kind.nativeValue);
    writer.writeInt(a);
    writer.writeInt(b);
    writer.writeString(message);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawCookieRecordExt on RawCookie {
  static RawCookie fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawCookie fromReader(RecordReader r) => RawCookie(
    name: r.readString(),
    value: r.readString(),
    domain: r.readString(),
    path: r.readString(),
    expiresEpochMs: r.readInt(),
    secure: r.readBool(),
    httpOnly: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(name);
    writer.writeString(value);
    writer.writeString(domain);
    writer.writeString(path);
    writer.writeInt(expiresEpochMs);
    writer.writeBool(secure);
    writer.writeBool(httpOnly);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawCacheConfigRecordExt on RawCacheConfig {
  static RawCacheConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawCacheConfig fromReader(RecordReader r) => RawCacheConfig(
    enabled: r.readBool(),
    directory: r.readString(),
    maxSizeBytes: r.readInt(),
    maxEntryBytes: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeBool(enabled);
    writer.writeString(directory);
    writer.writeInt(maxSizeBytes);
    writer.writeInt(maxEntryBytes);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawCacheStatsRecordExt on RawCacheStats {
  static RawCacheStats fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawCacheStats fromReader(RecordReader r) => RawCacheStats(
    entryCount: r.readInt(),
    sizeBytes: r.readInt(),
    hitCount: r.readInt(),
    missCount: r.readInt(),
    revalidationCount: r.readInt(),
    evictionCount: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(entryCount);
    writer.writeInt(sizeBytes);
    writer.writeInt(hitCount);
    writer.writeInt(missCount);
    writer.writeInt(revalidationCount);
    writer.writeInt(evictionCount);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawWsConfigRecordExt on RawWsConfig {
  static RawWsConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawWsConfig fromReader(RecordReader r) => RawWsConfig(
    socketId: r.readInt(),
    url: r.readString(),
    protocols: List.generate(r.readInt32(), (_) => r.readString()),
    headers: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
    pingIntervalMs: r.readInt(),
    maxFrameBytes: r.readInt(),
    connectTimeoutMs: r.readInt(),
    tls: RawTlsConfigRecordExt.fromReader(r),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(socketId);
    writer.writeString(url);
    writer.writeInt32(protocols.length);
    for (final e in protocols) {
      writer.writeString(e);
    }
    writer.writeInt32(headers.length);
    for (final e in headers) {
      e.writeFields(writer);
    }
    writer.writeInt(pingIntervalMs);
    writer.writeInt(maxFrameBytes);
    writer.writeInt(connectTimeoutMs);
    tls.writeFields(writer);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension RawWsHandshakeRecordExt on RawWsHandshake {
  static RawWsHandshake fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static RawWsHandshake fromReader(RecordReader r) => RawWsHandshake(
    socketId: r.readInt(),
    errorKind: r.readInt().toRawErrorKind(),
    errorMessage: r.readString(),
    engineErrorCode: r.readInt(),
    statusCode: r.readInt(),
    negotiatedProtocol: r.readString(),
    responseHeaders: List.generate(
      r.readInt32(),
      (_) => RawHeaderRecordExt.fromReader(r),
    ),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(socketId);
    writer.writeInt(errorKind.nativeValue);
    writer.writeString(errorMessage);
    writer.writeInt(engineErrorCode);
    writer.writeInt(statusCode);
    writer.writeString(negotiatedProtocol);
    writer.writeInt32(responseHeaders.length);
    for (final e in responseHeaders) {
      e.writeFields(writer);
    }
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _NitroHttpNativeImpl extends NitroHttpNative {
  final DynamicLibrary _dylib;
  static final _instances = <String, WeakReference<_NitroHttpNativeImpl>>{};

  static final _instanceFinalizer =
      Finalizer<
        ({
          int id,
          String key,
          Pointer<NitroErrorFfi> err,
          void Function(int) destroy,
        })
      >((t) {
        try {
          t.destroy(t.id);
          NitroRuntime.releaseLib('nitro_http');
          if (_instances[t.key]?.target == null) _instances.remove(t.key);
        } catch (_) {
        } finally {
          calloc.free(t.err);
        }
      });
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_http_nitro_free');
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_http_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_http_nitro_alloc');
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_http',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroHttpNativeImpl([String key = 'default']) {
    final cached = _instances[key]?.target;
    if (cached != null) return cached;
    return _NitroHttpNativeImpl._init(key);
  }

  _NitroHttpNativeImpl._init(this._instanceKey)
    : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_http: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_http_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_http: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_http_nitro_abi_version')) {
      throw StateError(
        'nitro_http: missing nitro_http_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_http',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_http_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_http_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_http: missing nitro_http_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_http',
      '715636835eecebca',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_http_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    RawChunkProxy._init(_dylib);
    RawWsFrameProxy._init(_dylib);
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_http: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    _instances[_instanceKey] = WeakReference(this);
    _instanceFinalizer.attach(this, (
      id: _instanceId,
      key: _instanceKey,
      err: _nitroErr,
      destroy: _destroyInstancePtr,
    ), detach: this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_http)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_http_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_http_destroy_instance',
      );
  late final Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
  _engineVersionPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_http_engine_version');
  late final bool Function(int, Pointer<NitroErrorFfi>) _supportsHttp3Ptr =
      _dylib
          .lookup<NativeFunction<Bool Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_supports_http3',
          )
          .asFunction<bool Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final bool Function(int, Pointer<NitroErrorFfi>) _supportsWebSocketsPtr =
      _dylib
          .lookup<NativeFunction<Bool Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_supports_web_sockets',
          )
          .asFunction<bool Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final bool Function(int, Pointer<NitroErrorFfi>) _supportsBrotliPtr =
      _dylib
          .lookup<NativeFunction<Bool Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_supports_brotli',
          )
          .asFunction<bool Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final bool Function(int, Pointer<NitroErrorFfi>) _supportsZstdPtr =
      _dylib
          .lookup<NativeFunction<Bool Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_supports_zstd',
          )
          .asFunction<bool Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _resetNativePtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_http_reset_native',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _configureClientPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_http_configure_client');
  late final void Function(
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    int,
    Pointer<NitroErrorFfi>,
    int,
  )
  _sendBufferedPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
          Int64,
        ),
        void Function(
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          int,
          Pointer<NitroErrorFfi>,
          int,
        )
      >('nitro_http_send_buffered');
  late final void Function(
    int,
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    int,
    int,
    Pointer<NitroErrorFfi>,
  )
  _sendBufferedCoalescedPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Size,
          Int64,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          int,
          int,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_http_send_buffered_coalesced');
  late final void Function(int, int, Pointer<NitroErrorFfi>) _releaseRecordPtr =
      _dylib
          .lookup<
            NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
          >('nitro_http_release_record')
          .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    int,
    Pointer<NitroErrorFfi>,
    int,
  )
  _startStreamedPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
          Int64,
        ),
        void Function(
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          int,
          Pointer<NitroErrorFfi>,
          int,
        )
      >('nitro_http_start_streamed');
  late final void Function(int, int, Pointer<NitroErrorFfi>) _cancelPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_http_cancel')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, Pointer<NitroErrorFfi>) _cancelAllPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_http_cancel_all',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _cancelTokenPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_http_cancel_token');
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _releaseCancelTokenPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_http_release_cancel_token')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, int, Pointer<NitroErrorFfi>)
  _grantCreditPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_http_grant_credit')
      .asFunction<void Function(int, int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final int Function(int, int, Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
  _feedUploadChunkPtr = _dylib
      .lookupFunction<
        Int64 Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
        ),
        int Function(int, int, Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
      >('nitro_http_feed_upload_chunk');
  late final void Function(int, int, Pointer<NitroErrorFfi>) _finishUploadPtr =
      _dylib
          .lookup<
            NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
          >('nitro_http_finish_upload')
          .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _failUploadPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_http_fail_upload');
  late final Pointer<Uint8> Function(int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _getCookiesPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_http_get_cookies');
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _setCookiePtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_http_set_cookie');
  late final void Function(int, Pointer<NitroErrorFfi>) _clearCookiesPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_clear_cookies',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _flushCookiesPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_http_flush_cookies',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _configureCachePtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_http_configure_cache');
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>, int)
  _prefetchPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>, Int64),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>, int)
      >('nitro_http_prefetch');
  late final void Function(int, Pointer<NitroErrorFfi>) _clearCachePtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_http_clear_cache',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
  _cacheStatsPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_http_cache_stats');
  late final void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>, int)
  _wsConnectPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Uint8>, Pointer<NitroErrorFfi>, Int64),
        void Function(int, Pointer<Uint8>, Pointer<NitroErrorFfi>, int)
      >('nitro_http_ws_connect');
  late final int Function(int, int, Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
  _wsSendPtr = _dylib
      .lookupFunction<
        Int64 Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Size,
          Pointer<NitroErrorFfi>,
        ),
        int Function(int, int, Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
      >('nitro_http_ws_send');
  late final void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _wsClosePtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(int, int, Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_http_ws_close');
  late final void Function(int, int, int, Pointer<NitroErrorFfi>)
  _wsGrantCreditPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_http_ws_grant_credit')
      .asFunction<void Function(int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int) _registerChunksPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_http_register_chunks_stream',
      );
  late final void Function(int) _releaseChunksPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_http_release_chunks_stream',
      );
  late final void Function(int, int) _registerEventsPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_http_register_events_stream',
      );
  late final void Function(int) _releaseEventsPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_http_release_events_stream',
      );
  late final void Function(int, int) _registerWsFramesPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_http_register_ws_frames_stream',
      );
  late final void Function(int) _releaseWsFramesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_http_release_ws_frames_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_http_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_http_clear_error',
      );

  @override
  void dispose() {
    if (isDisposed) return;
    _instanceFinalizer.detach(this);
    NitroRuntime.logLifecycle(
      'dispose(nitro_http)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_http');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_http)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  String engineVersion() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _engineVersionPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res.toDartStringBorrowed();
    }, methodName: 'engineVersion');
  }

  @override
  bool supportsHttp3() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _supportsHttp3Ptr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'supportsHttp3');
  }

  @override
  bool supportsWebSockets() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _supportsWebSocketsPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'supportsWebSockets');
  }

  @override
  bool supportsBrotli() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _supportsBrotliPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'supportsBrotli');
  }

  @override
  bool supportsZstd() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _supportsZstdPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'supportsZstd');
  }

  @override
  void resetNative() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _resetNativePtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'resetNative');
  }

  @override
  void configureClient(RawClientConfig config) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _configureClientPtr(_instanceId, config.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'configureClient',
    );
  }

  @override
  Future<RawResponse> sendBuffered(RawRequest request, Uint8List body) {
    checkDisposed();
    final arena = Arena();
    final _nitroErr = calloc<NitroErrorFfi>();
    try {
      return NitroRuntime.openNativeAsync<RawResponse>(
        call: (port) => _sendBufferedPtr(
          _instanceId,
          request.toNative(arena),
          body.toPointer(arena),
          body.length,
          _nitroErr,
          port,
        ),
        unpack: (raw) {
          NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
          return ((raw) {
            if (raw == null) {
              throw StateError(
                "sendBuffered (native-async): native posted null for a non-nullable RawResponse result — post the encoded value, or make the return type nullable",
              );
            }
            final rawPtr = Pointer<Uint8>.fromAddress(raw as int);
            try {
              return RawResponseRecordExt.fromNative(rawPtr);
            } finally {
              _nitroFree(rawPtr);
            }
          })(raw);
        },
        cleanup: () => calloc.free(_nitroErr),
        methodName: 'sendBuffered',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  void sendBufferedCoalesced(
    int callId,
    RawRequest request,
    Uint8List body,
    int dartPort,
  ) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _sendBufferedCoalescedPtr(
          _instanceId,
          callId,
          request.toNative(arena),
          body.toPointer(arena),
          body.length,
          dartPort,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'sendBufferedCoalesced',
    );
  }

  @override
  void releaseRecord(int address) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _releaseRecordPtr(_instanceId, address, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'releaseRecord');
  }

  @override
  Future<RawResponseHead> startStreamed(RawRequest request, Uint8List body) {
    checkDisposed();
    final arena = Arena();
    final _nitroErr = calloc<NitroErrorFfi>();
    try {
      return NitroRuntime.openNativeAsync<RawResponseHead>(
        call: (port) => _startStreamedPtr(
          _instanceId,
          request.toNative(arena),
          body.toPointer(arena),
          body.length,
          _nitroErr,
          port,
        ),
        unpack: (raw) {
          NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
          return ((raw) {
            if (raw == null) {
              throw StateError(
                "startStreamed (native-async): native posted null for a non-nullable RawResponseHead result — post the encoded value, or make the return type nullable",
              );
            }
            final rawPtr = Pointer<Uint8>.fromAddress(raw as int);
            try {
              return RawResponseHeadRecordExt.fromNative(rawPtr);
            } finally {
              _nitroFree(rawPtr);
            }
          })(raw);
        },
        cleanup: () => calloc.free(_nitroErr),
        methodName: 'startStreamed',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  void cancel(int requestId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _cancelPtr(_instanceId, requestId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'cancel');
  }

  @override
  void cancelAll() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _cancelAllPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'cancelAll');
  }

  @override
  void cancelToken(int tokenId, String reason) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _cancelTokenPtr(
          _instanceId,
          tokenId,
          reason.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'cancelToken',
    );
  }

  @override
  void releaseCancelToken(int tokenId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _releaseCancelTokenPtr(_instanceId, tokenId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'releaseCancelToken');
  }

  @override
  void grantCredit(int requestId, int chunkCount, int ackedChunks) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _grantCreditPtr(
        _instanceId,
        requestId,
        chunkCount,
        ackedChunks,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'grantCredit');
  }

  @override
  int feedUploadChunk(int requestId, Uint8List chunk) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _feedUploadChunkPtr(
          _instanceId,
          requestId,
          chunk.toPointer(arena),
          chunk.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        return res;
      }),
      methodName: 'feedUploadChunk',
    );
  }

  @override
  void finishUpload(int requestId) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _finishUploadPtr(_instanceId, requestId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'finishUpload');
  }

  @override
  void failUpload(int requestId, String message) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _failUploadPtr(
          _instanceId,
          requestId,
          message.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'failUpload',
    );
  }

  @override
  List<RawCookie> getCookies(String url) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _getCookiesPtr(
          _instanceId,
          url.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        return LazyRecordList.decode(
          res,
          (r) => RawCookieRecordExt.fromReader(r),
          nativeFree: _nitroFreeFinalizer,
        );
      }),
      methodName: 'getCookies',
    );
  }

  @override
  void setCookie(RawCookie cookie) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _setCookiePtr(_instanceId, cookie.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'setCookie',
    );
  }

  @override
  void clearCookies() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _clearCookiesPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'clearCookies');
  }

  @override
  void flushCookies() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _flushCookiesPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'flushCookies');
  }

  @override
  void configureCache(RawCacheConfig config) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _configureCachePtr(_instanceId, config.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'configureCache',
    );
  }

  @override
  Future<RawResponse> prefetch(RawRequest request) {
    checkDisposed();
    final arena = Arena();
    final _nitroErr = calloc<NitroErrorFfi>();
    try {
      return NitroRuntime.openNativeAsync<RawResponse>(
        call: (port) =>
            _prefetchPtr(_instanceId, request.toNative(arena), _nitroErr, port),
        unpack: (raw) {
          NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
          return ((raw) {
            if (raw == null) {
              throw StateError(
                "prefetch (native-async): native posted null for a non-nullable RawResponse result — post the encoded value, or make the return type nullable",
              );
            }
            final rawPtr = Pointer<Uint8>.fromAddress(raw as int);
            try {
              return RawResponseRecordExt.fromNative(rawPtr);
            } finally {
              _nitroFree(rawPtr);
            }
          })(raw);
        },
        cleanup: () => calloc.free(_nitroErr),
        methodName: 'prefetch',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  void clearCache() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _clearCachePtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'clearCache');
  }

  @override
  RawCacheStats cacheStats() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _cacheStatsPtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      final RawCacheStats decoded;
      try {
        decoded = RawCacheStatsRecordExt.fromNative(res);
      } finally {
        _nitroFree(res);
      }
      return decoded;
    }, methodName: 'cacheStats');
  }

  @override
  Future<RawWsHandshake> wsConnect(RawWsConfig config) {
    checkDisposed();
    final arena = Arena();
    final _nitroErr = calloc<NitroErrorFfi>();
    try {
      return NitroRuntime.openNativeAsync<RawWsHandshake>(
        call: (port) =>
            _wsConnectPtr(_instanceId, config.toNative(arena), _nitroErr, port),
        unpack: (raw) {
          NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
          return ((raw) {
            if (raw == null) {
              throw StateError(
                "wsConnect (native-async): native posted null for a non-nullable RawWsHandshake result — post the encoded value, or make the return type nullable",
              );
            }
            final rawPtr = Pointer<Uint8>.fromAddress(raw as int);
            try {
              return RawWsHandshakeRecordExt.fromNative(rawPtr);
            } finally {
              _nitroFree(rawPtr);
            }
          })(raw);
        },
        cleanup: () => calloc.free(_nitroErr),
        methodName: 'wsConnect',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  int wsSend(int opcode, Uint8List payload) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _wsSendPtr(
          _instanceId,
          opcode,
          payload.toPointer(arena),
          payload.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
        return res;
      }),
      methodName: 'wsSend',
    );
  }

  @override
  void wsClose(int code, String reason) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _wsClosePtr(
          _instanceId,
          code,
          reason.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      }),
      methodName: 'wsClose',
    );
  }

  @override
  void wsGrantCredit(int frameCount, int ackedFrames) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _wsGrantCreditPtr(_instanceId, frameCount, ackedFrames, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'wsGrantCredit');
  }

  @override
  Stream<RawChunk> get chunks {
    checkDisposed();
    return NitroRuntime.openStream<RawChunkProxy>(
      register: (port) => _registerChunksPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError('Received null event on non-nullable stream chunks');
        }
        return RawChunkProxy(Pointer<RawChunkFfi>.fromAddress(message as int));
      },
      release: (port) => _releaseChunksPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }

  @override
  Stream<RawEvent> get events {
    checkDisposed();
    return NitroRuntime.openStream<RawEvent>(
      register: (port) => _registerEventsPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError('Received null event on non-nullable stream events');
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return RawEventRecordExt.fromNative(rawPtr);
        } finally {
          _nitroFree(rawPtr);
        }
      },
      release: (port) => _releaseEventsPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }

  @override
  Stream<RawWsFrame> get wsFrames {
    checkDisposed();
    return NitroRuntime.openStream<RawWsFrameProxy>(
      register: (port) => _registerWsFramesPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream wsFrames',
          );
        }
        return RawWsFrameProxy(
          Pointer<RawWsFrameFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseWsFramesPtr(port),
      backpressure: Backpressure.bufferDrop,
    );
  }
}

extension NitroHttpNativeNativeRef on NitroHttpNative {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroHttpNativeImpl).asAnyNativeObject;
}
