// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.5
// Generated from: nitro_http.native.dart
// spec-sha256: e6bb1cae1237fa4f0665d2bd2c71df03d496271a4c92cf65279510ffcc0eb2ef
/// Platform-conditional factory for [NitroHttpNative]:
///
/// ```dart
/// import 'nitro_http.platform.g.dart';
///
/// await ensureNitroHttpNativeReady();               // no-op on native
/// final api = createNitroHttpNativeInstance();
/// ```
library;

export 'generated/native/nitro_http.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_http.web.bridge.g.dart'
    show createNitroHttpNativeInstance, ensureNitroHttpNativeReady;
