// Starter browser test generated by `nitrogen link`, kept out of `test/` so
// `flutter test` does not try to run a @TestOn('browser') file on the VM.
//
// nitro_http does not load the WASM bridge in a browser — `executor_web.dart`
// serves web through `fetch` — so this only proves the module still builds and
// its ABI matches. The behaviour that matters on web is covered by the ordinary
// suite running against `WebRequestExecutor`.
//
// Build the module first, then run under BOTH web compilers — they differ at
// the js_interop boundary, so a green dart2js run does not imply dart2wasm:
//   web/build_web.sh
//   dart test -p chrome
//   dart test -p chrome -c dart2wasm
@TestOn('browser')
library;

import 'package:test/test.dart';

import 'package:nitro_http/src/nitro_http.native.dart';
// ensureNitroHttpNativeReady lives in the generated platform shim. It is imported
// directly because a package barrel does not necessarily re-export it — add
// `export 'src/nitro_http.platform.g.dart';` to the barrel if you want callers of
// your package to reach it too (web callers must await it before first use).
import 'package:nitro_http/src/nitro_http.platform.g.dart';

void main() {
  setUpAll(() async {
    final channel = spawnHybridUri('asset_server.dart');
    // dart2wasm hands JS numbers over as double — never cast with `as int`.
    final port = ((await channel.stream.first)! as num).toInt();
    await ensureNitroHttpNativeReady(jsUrl: 'http://localhost:$port/nitro_http.js');
  });

  test('module loads and the bridge answers', () {
    // Reaching here means the WASM module instantiated and the ABI-version
    // and bridge-checksum checks passed. Add real round-trips below.
    expect(NitroHttpNative.engine, isNotNull);
  });
}
