#!/bin/sh
# Regenerates src/engine/mozilla_roots.inc — the compiled-in Mozilla CA bundle
# that serves `rootCaSource == bundled` and the last-resort fallback when
# platform trust cannot be loaded.
#
# Run it whenever curl publishes a new extract; the bundle is a snapshot and a
# stale snapshot is a security liability. Never hand-edit the .inc: only text
# that came out of this script has provenance.
#
# Usage: tool/gen_mozilla_roots.sh [url]
set -eu

url=${1:-https://curl.se/ca/cacert.pem}
root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/src/engine/mozilla_roots.inc"

tmp=$(mktemp "${TMPDIR:-/tmp}/cacert.XXXXXX")
trap 'rm -f "$tmp"' EXIT INT TERM

curl -fsSL --retry 3 "$url" -o "$tmp"

if ! grep -q -- '-----BEGIN CERTIFICATE-----' "$tmp"; then
  echo "gen_mozilla_roots: $url returned no certificates; refusing to write" >&2
  exit 1
fi

# The delimiter of the generated raw string literal. If the bundle ever contains
# it, silently emitting it would truncate the literal and produce a bundle that
# compiles yet trusts the wrong set of roots.
if grep -q ')PEM"' "$tmp"; then
  echo "gen_mozilla_roots: bundle contains the raw-literal delimiter" >&2
  exit 1
fi

# Only the certificate blocks are emitted: curl's subject labels carry non-ASCII
# names, and a source file whose encoding matters is a portability trap for no
# gain. The provenance line is preserved as a comment instead.
stamp=$(sed -n 's/^## Certificate data from Mozilla as of: *//p' "$tmp" | head -1)
[ -n "$stamp" ] || stamp="unknown (source carried no date stamp)"
count=$(grep -c -- '-----BEGIN CERTIFICATE-----' "$tmp")

awk -v max=12000 -v url="$url" -v stamp="$stamp" -v count="$count" '
BEGIN {
  print "// Generated by tool/gen_mozilla_roots.sh — do not edit."
  print "//"
  print "// Source:   " url
  print "// Extract:  " stamp
  print "// Contains: " count " root certificates"
  print "//"
  print "// A comma-separated list of raw string literal chunks, concatenated once by"
  print "// CertStore::bundledRootsPem(). Split at certificate boundaries because MSVC"
  print "// caps a SINGLE string literal at 16380 bytes (C2026). The chunks are"
  print "// separate array elements, never concatenated by the compiler, so no other"
  print "// limit applies. max=12000 leaves room for the certificate that closes a"
  print "// chunk after the threshold is crossed."
  printf "R\"PEM("
}
/^-----BEGIN CERTIFICATE-----$/ { incert = 1 }
incert { print $0; n += length($0) + 1 }
/^-----END CERTIFICATE-----$/ {
  incert = 0
  if (n >= max) { print ")PEM\","; printf "R\"PEM("; n = 0 }
}
END { print ")PEM\"," }
' "$tmp" > "$out"

echo "gen_mozilla_roots: wrote $out ($count certificates, extract $stamp)"
