/// The description of one HTTP request, independent of which client sends it.
///
/// Immutable and library-agnostic on purpose: the console edits a draft, the
/// benchmark replays the same object thousands of times, and every
/// `HttpSender` reads the same fields. A client that cannot honour a field says
/// so through `SenderCapabilities` rather than silently ignoring it.
library;

import 'package:flutter/foundation.dart';

/// One editable name/value row, as used for headers, query parameters and form
/// fields.
///
/// [enabled] exists because a request console needs to park a header without
/// losing what it said — the same reason Postman has a checkbox per row.
@immutable
final class KeyValueRow {
  /// Creates a row.
  const KeyValueRow({
    required this.name,
    required this.value,
    this.enabled = true,
  });

  /// The field name. Empty rows are ignored when building a request.
  final String name;

  /// The field value. May be empty: `?flag=` and `X-Flag;` are both legal.
  final String value;

  /// Whether this row is sent.
  final bool enabled;

  /// Returns a copy with the given fields replaced.
  KeyValueRow copyWith({String? name, String? value, bool? enabled}) =>
      KeyValueRow(
        name: name ?? this.name,
        value: value ?? this.value,
        enabled: enabled ?? this.enabled,
      );

  /// Whether this row contributes anything.
  bool get isUsable => enabled && name.trim().isNotEmpty;

  @override
  bool operator ==(Object other) =>
      other is KeyValueRow &&
      other.name == name &&
      other.value == value &&
      other.enabled == enabled;

  @override
  int get hashCode => Object.hash(name, value, enabled);
}

/// What the request body is made of.
enum RequestBodyKind {
  /// No body at all.
  none('None'),

  /// A raw text body with an explicit content type.
  text('Text'),

  /// A JSON body. Sent as `application/json`; the console validates it.
  json('JSON'),

  /// `application/x-www-form-urlencoded`, built from the form rows.
  form('Form URL-encoded'),

  /// `multipart/form-data`, built from the form rows plus file parts.
  multipart('Multipart'),

  /// A file streamed from disk without loading it into the Dart heap.
  file('File'),

  /// Generated bytes of a given size, for throughput work.
  generatedBytes('Generated bytes');

  const RequestBodyKind(this.label);

  /// Human-readable name for pickers.
  final String label;

  /// Whether this kind carries a payload at all.
  bool get hasPayload => this != RequestBodyKind.none;
}

/// How the response body should be consumed.
enum ResponseMode {
  /// Buffer the whole body, then hand it over.
  buffered('Buffered'),

  /// Stream the body, reporting progress as it arrives.
  streamed('Streamed');

  const ResponseMode(this.label);

  /// Human-readable name for pickers.
  final String label;
}

/// One part of a multipart body.
@immutable
final class MultipartPart {
  /// Creates a part.
  const MultipartPart({
    required this.field,
    this.value = '',
    this.filePath,
    this.contentType,
    this.enabled = true,
  });

  /// The field name.
  final String field;

  /// The text value, used when [filePath] is null.
  final String value;

  /// A file to attach instead of [value].
  final String? filePath;

  /// An explicit content type for this part.
  final String? contentType;

  /// Whether this part is sent.
  final bool enabled;

  /// Whether this part attaches a file.
  bool get isFile => filePath != null && filePath!.isNotEmpty;

  /// Returns a copy with the given fields replaced.
  MultipartPart copyWith({
    String? field,
    String? value,
    String? filePath,
    String? contentType,
    bool? enabled,
  }) => MultipartPart(
    field: field ?? this.field,
    value: value ?? this.value,
    filePath: filePath ?? this.filePath,
    contentType: contentType ?? this.contentType,
    enabled: enabled ?? this.enabled,
  );
}

/// Everything needed to issue one request.
@immutable
final class RequestSpec {
  /// Creates a spec.
  const RequestSpec({
    this.method = 'GET',
    this.url = '',
    this.query = const <KeyValueRow>[],
    this.headers = const <KeyValueRow>[],
    this.bodyKind = RequestBodyKind.none,
    this.bodyText = '',
    this.formFields = const <KeyValueRow>[],
    this.parts = const <MultipartPart>[],
    this.filePath,
    this.generatedByteCount = 1024 * 1024,
    this.contentTypeOverride,
    this.responseMode = ResponseMode.buffered,
    this.followRedirects = true,
    this.maxRedirects = 5,
    this.connectTimeout,
    this.totalTimeout,
    this.sendCookies = true,
    this.acceptEncoding = true,
  });

  /// The HTTP verb. A free string, so `PROPFIND` works, not just the common six.
  final String method;

  /// The absolute request URL, or a path resolved against the demo server.
  final String url;

  /// Query parameters appended to [url].
  final List<KeyValueRow> query;

  /// Request headers. A row here replaces a client default of the same name.
  final List<KeyValueRow> headers;

  /// What the body is made of.
  final RequestBodyKind bodyKind;

  /// The raw text or JSON body, for [RequestBodyKind.text] and
  /// [RequestBodyKind.json].
  final String bodyText;

  /// Fields for [RequestBodyKind.form].
  final List<KeyValueRow> formFields;

  /// Parts for [RequestBodyKind.multipart].
  final List<MultipartPart> parts;

  /// The file for [RequestBodyKind.file].
  final String? filePath;

  /// How many bytes to synthesise for [RequestBodyKind.generatedBytes].
  final int generatedByteCount;

  /// Overrides the content type the body kind would otherwise imply.
  final String? contentTypeOverride;

  /// Whether the body is buffered or streamed on the way back.
  final ResponseMode responseMode;

  /// Whether 3xx responses are followed.
  final bool followRedirects;

  /// The redirect limit when [followRedirects] is set.
  final int maxRedirects;

  /// Connect-phase timeout, or null for the client default.
  final Duration? connectTimeout;

  /// Whole-request timeout, or null for the client default.
  final Duration? totalTimeout;

  /// Whether the client's cookie jar participates.
  final bool sendCookies;

  /// Whether to advertise `Accept-Encoding` and decode the response.
  final bool acceptEncoding;

  /// Returns a copy with the given fields replaced.
  ///
  /// `filePath`, `contentTypeOverride`, `connectTimeout` and `totalTimeout` are
  /// nullable fields, so each has a matching `clearX` flag: passing null alone
  /// cannot distinguish "leave it" from "unset it".
  RequestSpec copyWith({
    String? method,
    String? url,
    List<KeyValueRow>? query,
    List<KeyValueRow>? headers,
    RequestBodyKind? bodyKind,
    String? bodyText,
    List<KeyValueRow>? formFields,
    List<MultipartPart>? parts,
    String? filePath,
    bool clearFilePath = false,
    int? generatedByteCount,
    String? contentTypeOverride,
    bool clearContentTypeOverride = false,
    ResponseMode? responseMode,
    bool? followRedirects,
    int? maxRedirects,
    Duration? connectTimeout,
    bool clearConnectTimeout = false,
    Duration? totalTimeout,
    bool clearTotalTimeout = false,
    bool? sendCookies,
    bool? acceptEncoding,
  }) => RequestSpec(
    method: method ?? this.method,
    url: url ?? this.url,
    query: query ?? this.query,
    headers: headers ?? this.headers,
    bodyKind: bodyKind ?? this.bodyKind,
    bodyText: bodyText ?? this.bodyText,
    formFields: formFields ?? this.formFields,
    parts: parts ?? this.parts,
    filePath: clearFilePath ? null : (filePath ?? this.filePath),
    generatedByteCount: generatedByteCount ?? this.generatedByteCount,
    contentTypeOverride: clearContentTypeOverride
        ? null
        : (contentTypeOverride ?? this.contentTypeOverride),
    responseMode: responseMode ?? this.responseMode,
    followRedirects: followRedirects ?? this.followRedirects,
    maxRedirects: maxRedirects ?? this.maxRedirects,
    connectTimeout: clearConnectTimeout
        ? null
        : (connectTimeout ?? this.connectTimeout),
    totalTimeout: clearTotalTimeout ? null : (totalTimeout ?? this.totalTimeout),
    sendCookies: sendCookies ?? this.sendCookies,
    acceptEncoding: acceptEncoding ?? this.acceptEncoding,
  );

  /// The rows that will actually be sent.
  Iterable<KeyValueRow> get effectiveHeaders => headers.where((h) => h.isUsable);

  /// The query rows that will actually be sent.
  Iterable<KeyValueRow> get effectiveQuery => query.where((q) => q.isUsable);

  /// The full URL including [query], resolved against [baseUrl] when [url] is a
  /// bare path.
  ///
  /// Returns null when the result is not a parseable URI, which is what lets the
  /// console disable Send rather than throwing on a half-typed address.
  Uri? resolve({required String baseUrl}) {
    final raw = url.trim();
    if (raw.isEmpty) return null;
    final joined = raw.startsWith('http://') || raw.startsWith('https://')
        ? raw
        : '$baseUrl${raw.startsWith('/') ? '' : '/'}$raw';
    final parsed = Uri.tryParse(joined);
    if (parsed == null || parsed.host.isEmpty) return null;
    final extra = <String, String>{
      for (final row in effectiveQuery) row.name.trim(): row.value,
    };
    if (extra.isEmpty) return parsed;
    return parsed.replace(
      queryParameters: <String, String>{...parsed.queryParameters, ...extra},
    );
  }

  /// Whether this spec is complete enough to send against [baseUrl].
  bool isSendable({required String baseUrl}) =>
      method.trim().isNotEmpty && resolve(baseUrl: baseUrl) != null;
}
