// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.4
// Generated from: nitro_http.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifndef NITRO_OPT_DEFINED
#define NITRO_OPT_DEFINED
#pragma pack(push, 1)
typedef struct { uint8_t hasValue; int64_t  value; } NitroOptInt64;
typedef struct { uint8_t hasValue; double   value; } NitroOptFloat64;
typedef struct { uint8_t hasValue; uint8_t  value; } NitroOptBool;
#pragma pack(pop)
#endif

// --- Enums ---
typedef enum {
  RAWMETHOD_GET = 0,
  RAWMETHOD_HEAD = 1,
  RAWMETHOD_POST = 2,
  RAWMETHOD_PUT = 3,
  RAWMETHOD_DELETE = 4,
  RAWMETHOD_PATCH = 5,
  RAWMETHOD_OPTIONS = 6,
  RAWMETHOD_TRACE = 7,
  RAWMETHOD_CUSTOM = 8,
} RawMethod;

typedef enum {
  RAWHTTPVERSIONPREF_AUTO = 0,
  RAWHTTPVERSIONPREF_HTTP11_ONLY = 1,
  RAWHTTPVERSIONPREF_HTTP2 = 2,
  RAWHTTPVERSIONPREF_HTTP2_ONLY = 3,
  RAWHTTPVERSIONPREF_HTTP3 = 4,
  RAWHTTPVERSIONPREF_HTTP3_ONLY = 5,
} RawHttpVersionPref;

typedef enum {
  RAWHTTPVERSION_UNKNOWN = 0,
  RAWHTTPVERSION_HTTP10 = 1,
  RAWHTTPVERSION_HTTP11 = 2,
  RAWHTTPVERSION_HTTP2 = 3,
  RAWHTTPVERSION_HTTP3 = 4,
} RawHttpVersion;

typedef enum {
  RAWERRORKIND_NONE = 0,
  RAWERRORKIND_CANCELLED = 1,
  RAWERRORKIND_TIMEOUT_CONNECT = 2,
  RAWERRORKIND_TIMEOUT_REQUEST = 3,
  RAWERRORKIND_TIMEOUT_IDLE = 4,
  RAWERRORKIND_DNS_FAILURE = 5,
  RAWERRORKIND_CONNECTION_REFUSED = 6,
  RAWERRORKIND_CONNECTION_RESET = 7,
  RAWERRORKIND_CONNECTION_FAILED = 8,
  RAWERRORKIND_TLS_HANDSHAKE = 9,
  RAWERRORKIND_CERTIFICATE_INVALID = 10,
  RAWERRORKIND_CERTIFICATE_PIN_MISMATCH = 11,
  RAWERRORKIND_CERTIFICATE_CLIENT_AUTH = 12,
  RAWERRORKIND_TOO_MANY_REDIRECTS = 13,
  RAWERRORKIND_PROXY_FAILURE = 14,
  RAWERRORKIND_PROTOCOL_ERROR = 15,
  RAWERRORKIND_UNSUPPORTED_SCHEME = 16,
  RAWERRORKIND_SEND_FAILURE = 17,
  RAWERRORKIND_RECEIVE_FAILURE = 18,
  RAWERRORKIND_DECOMPRESSION_FAILURE = 19,
  RAWERRORKIND_RESPONSE_TOO_LARGE = 20,
  RAWERRORKIND_IO = 21,
  RAWERRORKIND_CACHE_MISS = 22,
  RAWERRORKIND_ENGINE_ERROR = 23,
  RAWERRORKIND_BAD_REQUEST = 24,
  RAWERRORKIND_UNKNOWN = 25,
} RawErrorKind;

typedef enum {
  RAWPROXYMODE_SYSTEM = 0,
  RAWPROXYMODE_NONE = 1,
  RAWPROXYMODE_HTTP = 2,
  RAWPROXYMODE_SOCKS5 = 3,
  RAWPROXYMODE_SOCKS5_HOSTNAME = 4,
} RawProxyMode;

typedef enum {
  RAWCACHEMODE_NORMAL = 0,
  RAWCACHEMODE_NO_STORE = 1,
  RAWCACHEMODE_BYPASS = 2,
  RAWCACHEMODE_ONLY_IF_CACHED = 3,
  RAWCACHEMODE_REFRESH = 4,
} RawCacheMode;

typedef enum {
  RAWBODYKIND_NONE = 0,
  RAWBODYKIND_BYTES = 1,
  RAWBODYKIND_FILE_PATH = 2,
  RAWBODYKIND_STREAMED = 3,
} RawBodyKind;

typedef enum {
  RAWCHUNKKIND_DATA = 0,
  RAWCHUNKKIND_DONE = 1,
  RAWCHUNKKIND_ERROR = 2,
} RawChunkKind;

typedef enum {
  RAWEVENTKIND_DOWNLOAD_PROGRESS = 0,
  RAWEVENTKIND_UPLOAD_PROGRESS = 1,
  RAWEVENTKIND_UPLOAD_DRAIN = 2,
  RAWEVENTKIND_NOTICE = 3,
} RawEventKind;

// --- Structs ---
#ifndef NITRO_STRUCT_RAWCHUNK_DEFINED
#define NITRO_STRUCT_RAWCHUNK_DEFINED
typedef struct {
  uint8_t* bytes; /* zero-copy */
  int64_t bytesLength; /* synthesized: element count for zero-copy buffer */
  int64_t requestId; 
  int64_t kind; 
  int64_t aux; 
} RawChunk;
#endif // NITRO_STRUCT_RAWCHUNK_DEFINED

#ifndef NITRO_STRUCT_RAWWSFRAME_DEFINED
#define NITRO_STRUCT_RAWWSFRAME_DEFINED
typedef struct {
  uint8_t* payload; /* zero-copy */
  int64_t payloadLength; /* synthesized: element count for zero-copy buffer */
  int64_t socketId; 
  int64_t opcode; 
  int64_t flags; 
} RawWsFrame;
#endif // NITRO_STRUCT_RAWWSFRAME_DEFINED

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_http_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_http_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_http_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_http_get_error(void);
NITRO_EXPORT void nitro_http_clear_error(void);
NITRO_EXPORT int64_t nitro_http_create_instance(const char* key);
NITRO_EXPORT void nitro_http_destroy_instance(int64_t instanceId);
NITRO_EXPORT void nitro_http_nitro_free(void* ptr);
NITRO_EXPORT void* nitro_http_nitro_alloc(size_t size);



// Methods
NITRO_EXPORT const char* nitro_http_engine_version(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_http_supports_http3(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_http_supports_web_sockets(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_http_supports_brotli(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_http_supports_zstd(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_reset_native(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_configure_client(int64_t instanceId, void* config, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_send_buffered(int64_t instanceId, void* request, uint8_t* body, size_t body_length, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT void nitro_http_send_buffered_coalesced(int64_t instanceId, int64_t callId, void* request, uint8_t* body, size_t body_length, int64_t dartPort, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_release_record(int64_t instanceId, int64_t address, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_start_streamed(int64_t instanceId, void* request, uint8_t* body, size_t body_length, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT void nitro_http_cancel(int64_t instanceId, int64_t requestId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_cancel_all(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_cancel_token(int64_t instanceId, int64_t tokenId, const char* reason, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_release_cancel_token(int64_t instanceId, int64_t tokenId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_grant_credit(int64_t instanceId, int64_t requestId, int64_t chunkCount, int64_t ackedChunks, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_http_feed_upload_chunk(int64_t instanceId, int64_t requestId, uint8_t* chunk, size_t chunk_length, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_finish_upload(int64_t instanceId, int64_t requestId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_fail_upload(int64_t instanceId, int64_t requestId, const char* message, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_http_get_cookies(int64_t instanceId, const char* url, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_set_cookie(int64_t instanceId, void* cookie, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_clear_cookies(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_flush_cookies(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_configure_cache(int64_t instanceId, void* config, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_prefetch(int64_t instanceId, void* request, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT void nitro_http_clear_cache(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_http_cache_stats(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_ws_connect(int64_t instanceId, void* config, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_http_ws_send(int64_t instanceId, int64_t opcode, uint8_t* payload, size_t payload_length, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_ws_close(int64_t instanceId, int64_t code, const char* reason, NitroError* _nitro_err);
NITRO_EXPORT void nitro_http_ws_grant_credit(int64_t instanceId, int64_t frameCount, int64_t ackedFrames, NitroError* _nitro_err);

// Streams
// Stream<RawChunk> chunks
NITRO_EXPORT void nitro_http_register_chunks_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_http_release_chunks_stream(int64_t dart_port);
// Stream<RawEvent> events
NITRO_EXPORT void nitro_http_register_events_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_http_release_events_stream(int64_t dart_port);
// Stream<RawWsFrame> wsFrames
NITRO_EXPORT void nitro_http_register_ws_frames_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_http_release_ws_frames_stream(int64_t dart_port);

// Struct release functions
NITRO_EXPORT void nitro_http_release_RawChunk(void* ptr);
NITRO_EXPORT void nitro_http_release_RawWsFrame(void* ptr);

#ifdef __cplusplus
}
#endif
