// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.4
// Generated from: nitro_http.native.dart
import Foundation
import Combine

// This file is SELF-CONTAINED: the shared codec types (NitroEncodable,
// NitroRecordWriter, NitroRecordReader) are emitted below so an all-C++
// plugin (no Swift-impl module anywhere) still compiles. When a sibling
// Swift-impl bridge is compiled into the same module, nitrogen's sync
// dedup pass keeps exactly one copy of each shared declaration.
//
// No @_cdecl stubs are generated: the C++ bridge (.bridge.g.mm) calls
// nitro_http_xxx C functions directly — Swift @_cdecl stubs are unused
// and would conflict with the Swift module's exported symbols.

public protocol NitroEncodable {
    func toNative() -> UnsafeMutablePointer<UInt8>?
}

// --- Enums ---
public enum RawMethod: Int64 {
  case get = 0
  case head = 1
  case post = 2
  case put = 3
  case delete = 4
  case patch = 5
  case options = 6
  case trace = 7
  case custom = 8
}

public enum RawHttpVersionPref: Int64 {
  case auto = 0
  case http11Only = 1
  case http2 = 2
  case http2Only = 3
  case http3 = 4
  case http3Only = 5
}

public enum RawHttpVersion: Int64 {
  case unknown = 0
  case http10 = 1
  case http11 = 2
  case http2 = 3
  case http3 = 4
}

public enum RawErrorKind: Int64 {
  case none = 0
  case cancelled = 1
  case timeoutConnect = 2
  case timeoutRequest = 3
  case timeoutIdle = 4
  case dnsFailure = 5
  case connectionRefused = 6
  case connectionReset = 7
  case connectionFailed = 8
  case tlsHandshake = 9
  case certificateInvalid = 10
  case certificatePinMismatch = 11
  case certificateClientAuth = 12
  case tooManyRedirects = 13
  case proxyFailure = 14
  case protocolError = 15
  case unsupportedScheme = 16
  case sendFailure = 17
  case receiveFailure = 18
  case decompressionFailure = 19
  case responseTooLarge = 20
  case io = 21
  case cacheMiss = 22
  case engineError = 23
  case badRequest = 24
  case unknown = 25
}

public enum RawProxyMode: Int64 {
  case system = 0
  case none = 1
  case http = 2
  case socks5 = 3
  case socks5Hostname = 4
}

public enum RawCacheMode: Int64 {
  case normal = 0
  case noStore = 1
  case bypass = 2
  case onlyIfCached = 3
  case refresh = 4
}

public enum RawBodyKind: Int64 {
  case none = 0
  case bytes = 1
  case filePath = 2
  case streamed = 3
}

public enum RawChunkKind: Int64 {
  case data = 0
  case done = 1
  case error = 2
}

public enum RawEventKind: Int64 {
  case downloadProgress = 0
  case uploadProgress = 1
  case uploadDrain = 2
  case notice = 3
}

// --- Structs ---
public struct RawChunk {
  public var bytes: UnsafeMutablePointer<UInt8>?
  public var bytesLength: Int64
  public var requestId: Int64
  public var kind: Int64
  public var aux: Int64
}

// C-ABI shadow — layout matches the C typedef RawChunk
fileprivate struct _RawChunkC {
  var bytes: UnsafeMutablePointer<UInt8>?
  var bytesLength: Int64
  var requestId: Int64
  var kind: Int64
  var aux: Int64

  static func fromSwift(_ s: RawChunk) -> _RawChunkC {
    return _RawChunkC(
      bytes: s.bytes,
      bytesLength: s.bytesLength,
      requestId: s.requestId,
      kind: s.kind,
      aux: s.aux
    )
  }

  static func fromSwiftPtr(_ s: RawChunk) -> UnsafeMutablePointer<_RawChunkC> {
    let p = UnsafeMutablePointer<_RawChunkC>.allocate(capacity: 1)
    p.initialize(to: fromSwift(s))
    return p
  }

  func toSwift() -> RawChunk {
    return RawChunk(
      bytes: bytes,
      bytesLength: bytesLength,
      requestId: requestId,
      kind: kind,
      aux: aux
    )
  }
}

public struct RawWsFrame {
  public var payload: UnsafeMutablePointer<UInt8>?
  public var payloadLength: Int64
  public var socketId: Int64
  public var opcode: Int64
  public var flags: Int64
}

// C-ABI shadow — layout matches the C typedef RawWsFrame
fileprivate struct _RawWsFrameC {
  var payload: UnsafeMutablePointer<UInt8>?
  var payloadLength: Int64
  var socketId: Int64
  var opcode: Int64
  var flags: Int64

  static func fromSwift(_ s: RawWsFrame) -> _RawWsFrameC {
    return _RawWsFrameC(
      payload: s.payload,
      payloadLength: s.payloadLength,
      socketId: s.socketId,
      opcode: s.opcode,
      flags: s.flags
    )
  }

  static func fromSwiftPtr(_ s: RawWsFrame) -> UnsafeMutablePointer<_RawWsFrameC> {
    let p = UnsafeMutablePointer<_RawWsFrameC>.allocate(capacity: 1)
    p.initialize(to: fromSwift(s))
    return p
  }

  func toSwift() -> RawWsFrame {
    return RawWsFrame(
      payload: payload,
      payloadLength: payloadLength,
      socketId: socketId,
      opcode: opcode,
      flags: flags
    )
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

public struct RawHeader: NitroEncodable {
  public var name: String
  public var value: String

  public init(name: String, value: String) {
    self.name = name
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawHeader {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawHeader {
    return RawHeader(
      name: r.readString(),
      value: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(name)
    writer.writeString(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawTlsConfig: NitroEncodable {
  public var verifyCertificates: Bool
  public var rootCaSource: Int64
  public var trustedRootsPem: String
  public var clientCertPem: String
  public var clientKeyPem: String
  public var clientKeyPassword: String
  public var pinnedSpkiSha256: [String]
  public var minTlsVersion: Int64
  public var maxTlsVersion: Int64
  public var sniHostname: String

  public init(verifyCertificates: Bool, rootCaSource: Int64, trustedRootsPem: String, clientCertPem: String, clientKeyPem: String, clientKeyPassword: String, pinnedSpkiSha256: [String], minTlsVersion: Int64, maxTlsVersion: Int64, sniHostname: String) {
    self.verifyCertificates = verifyCertificates
    self.rootCaSource = rootCaSource
    self.trustedRootsPem = trustedRootsPem
    self.clientCertPem = clientCertPem
    self.clientKeyPem = clientKeyPem
    self.clientKeyPassword = clientKeyPassword
    self.pinnedSpkiSha256 = pinnedSpkiSha256
    self.minTlsVersion = minTlsVersion
    self.maxTlsVersion = maxTlsVersion
    self.sniHostname = sniHostname
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawTlsConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawTlsConfig {
    return RawTlsConfig(
      verifyCertificates: r.readBool(),
      rootCaSource: r.readInt(),
      trustedRootsPem: r.readString(),
      clientCertPem: r.readString(),
      clientKeyPem: r.readString(),
      clientKeyPassword: r.readString(),
      pinnedSpkiSha256: (0..<Int(r.readInt32())).map { _ in r.readString() },
      minTlsVersion: r.readInt(),
      maxTlsVersion: r.readInt(),
      sniHostname: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(verifyCertificates)
    writer.writeInt(rootCaSource)
    writer.writeString(trustedRootsPem)
    writer.writeString(clientCertPem)
    writer.writeString(clientKeyPem)
    writer.writeString(clientKeyPassword)
    writer.writeInt32(Int32(pinnedSpkiSha256.count))
    for e in pinnedSpkiSha256 { writer.writeString(e) }
    writer.writeInt(minTlsVersion)
    writer.writeInt(maxTlsVersion)
    writer.writeString(sniHostname)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawProxyConfig: NitroEncodable {
  public var mode: RawProxyMode
  public var url: String
  public var username: String
  public var password: String
  public var noProxyHosts: String

  public init(mode: RawProxyMode, url: String, username: String, password: String, noProxyHosts: String) {
    self.mode = mode
    self.url = url
    self.username = username
    self.password = password
    self.noProxyHosts = noProxyHosts
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawProxyConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawProxyConfig {
    return RawProxyConfig(
      mode: RawProxyMode(rawValue: r.readInt())!,
      url: r.readString(),
      username: r.readString(),
      password: r.readString(),
      noProxyHosts: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(mode.rawValue)
    writer.writeString(url)
    writer.writeString(username)
    writer.writeString(password)
    writer.writeString(noProxyHosts)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawDnsConfig: NitroEncodable {
  public var staticOverrides: [String]
  public var dohUrl: String

  public init(staticOverrides: [String], dohUrl: String) {
    self.staticOverrides = staticOverrides
    self.dohUrl = dohUrl
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawDnsConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawDnsConfig {
    return RawDnsConfig(
      staticOverrides: (0..<Int(r.readInt32())).map { _ in r.readString() },
      dohUrl: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt32(Int32(staticOverrides.count))
    for e in staticOverrides { writer.writeString(e) }
    writer.writeString(dohUrl)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawCookieConfig: NitroEncodable {
  public var enabled: Bool
  public var persistPath: String

  public init(enabled: Bool, persistPath: String) {
    self.enabled = enabled
    self.persistPath = persistPath
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawCookieConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawCookieConfig {
    return RawCookieConfig(
      enabled: r.readBool(),
      persistPath: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(enabled)
    writer.writeString(persistPath)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawPoolConfig: NitroEncodable {
  public var maxConnections: Int64
  public var maxConnectionsPerHost: Int64
  public var idleTimeoutMs: Int64
  public var maxLifetimeMs: Int64
  public var keepAlivePingMs: Int64

  public init(maxConnections: Int64, maxConnectionsPerHost: Int64, idleTimeoutMs: Int64, maxLifetimeMs: Int64, keepAlivePingMs: Int64) {
    self.maxConnections = maxConnections
    self.maxConnectionsPerHost = maxConnectionsPerHost
    self.idleTimeoutMs = idleTimeoutMs
    self.maxLifetimeMs = maxLifetimeMs
    self.keepAlivePingMs = keepAlivePingMs
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawPoolConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawPoolConfig {
    return RawPoolConfig(
      maxConnections: r.readInt(),
      maxConnectionsPerHost: r.readInt(),
      idleTimeoutMs: r.readInt(),
      maxLifetimeMs: r.readInt(),
      keepAlivePingMs: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(maxConnections)
    writer.writeInt(maxConnectionsPerHost)
    writer.writeInt(idleTimeoutMs)
    writer.writeInt(maxLifetimeMs)
    writer.writeInt(keepAlivePingMs)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawClientConfig: NitroEncodable {
  public var httpVersion: RawHttpVersionPref
  public var connectTimeoutMs: Int64
  public var requestTimeoutMs: Int64
  public var idleTimeoutMs: Int64
  public var followRedirects: Bool
  public var maxRedirects: Int64
  public var enableCompression: Bool
  public var enableCache: Bool
  public var userAgent: String
  public var altSvcCachePath: String
  public var streamChunkBytes: Int64
  public var streamChunkMinContentLength: Int64
  public var streamChunkMaxHoldMs: Int64
  public var maxResponseBytes: Int64
  public var hstsCachePath: String
  public var unixSocketPath: String
  public var networkInterface: String
  public var defaultHeaders: [RawHeader]
  public var tls: RawTlsConfig
  public var proxy: RawProxyConfig
  public var dns: RawDnsConfig
  public var cookies: RawCookieConfig
  public var pool: RawPoolConfig

  public init(httpVersion: RawHttpVersionPref, connectTimeoutMs: Int64, requestTimeoutMs: Int64, idleTimeoutMs: Int64, followRedirects: Bool, maxRedirects: Int64, enableCompression: Bool, enableCache: Bool, userAgent: String, altSvcCachePath: String, streamChunkBytes: Int64, streamChunkMinContentLength: Int64, streamChunkMaxHoldMs: Int64, maxResponseBytes: Int64, hstsCachePath: String, unixSocketPath: String, networkInterface: String, defaultHeaders: [RawHeader], tls: RawTlsConfig, proxy: RawProxyConfig, dns: RawDnsConfig, cookies: RawCookieConfig, pool: RawPoolConfig) {
    self.httpVersion = httpVersion
    self.connectTimeoutMs = connectTimeoutMs
    self.requestTimeoutMs = requestTimeoutMs
    self.idleTimeoutMs = idleTimeoutMs
    self.followRedirects = followRedirects
    self.maxRedirects = maxRedirects
    self.enableCompression = enableCompression
    self.enableCache = enableCache
    self.userAgent = userAgent
    self.altSvcCachePath = altSvcCachePath
    self.streamChunkBytes = streamChunkBytes
    self.streamChunkMinContentLength = streamChunkMinContentLength
    self.streamChunkMaxHoldMs = streamChunkMaxHoldMs
    self.maxResponseBytes = maxResponseBytes
    self.hstsCachePath = hstsCachePath
    self.unixSocketPath = unixSocketPath
    self.networkInterface = networkInterface
    self.defaultHeaders = defaultHeaders
    self.tls = tls
    self.proxy = proxy
    self.dns = dns
    self.cookies = cookies
    self.pool = pool
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawClientConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawClientConfig {
    return RawClientConfig(
      httpVersion: RawHttpVersionPref(rawValue: r.readInt())!,
      connectTimeoutMs: r.readInt(),
      requestTimeoutMs: r.readInt(),
      idleTimeoutMs: r.readInt(),
      followRedirects: r.readBool(),
      maxRedirects: r.readInt(),
      enableCompression: r.readBool(),
      enableCache: r.readBool(),
      userAgent: r.readString(),
      altSvcCachePath: r.readString(),
      streamChunkBytes: r.readInt(),
      streamChunkMinContentLength: r.readInt(),
      streamChunkMaxHoldMs: r.readInt(),
      maxResponseBytes: r.readInt(),
      hstsCachePath: r.readString(),
      unixSocketPath: r.readString(),
      networkInterface: r.readString(),
      defaultHeaders: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) },
      tls: RawTlsConfig.fromReader(r),
      proxy: RawProxyConfig.fromReader(r),
      dns: RawDnsConfig.fromReader(r),
      cookies: RawCookieConfig.fromReader(r),
      pool: RawPoolConfig.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(httpVersion.rawValue)
    writer.writeInt(connectTimeoutMs)
    writer.writeInt(requestTimeoutMs)
    writer.writeInt(idleTimeoutMs)
    writer.writeBool(followRedirects)
    writer.writeInt(maxRedirects)
    writer.writeBool(enableCompression)
    writer.writeBool(enableCache)
    writer.writeString(userAgent)
    writer.writeString(altSvcCachePath)
    writer.writeInt(streamChunkBytes)
    writer.writeInt(streamChunkMinContentLength)
    writer.writeInt(streamChunkMaxHoldMs)
    writer.writeInt(maxResponseBytes)
    writer.writeString(hstsCachePath)
    writer.writeString(unixSocketPath)
    writer.writeString(networkInterface)
    writer.writeInt32(Int32(defaultHeaders.count))
    for e in defaultHeaders { e.writeFields(writer) }
    tls.writeFields(writer)
    proxy.writeFields(writer)
    dns.writeFields(writer)
    cookies.writeFields(writer)
    pool.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawRequestOptions: NitroEncodable {
  public var connectTimeoutMs: Int64
  public var requestTimeoutMs: Int64
  public var followRedirects: Int64
  public var maxRedirects: Int64
  public var cacheMode: RawCacheMode
  public var reportProgress: Bool
  public var wantTimings: Bool
  public var uploadContentLength: Int64
  public var pinnedSpkiOverride: String
  public var cancelTokenId: Int64

  public init(connectTimeoutMs: Int64, requestTimeoutMs: Int64, followRedirects: Int64, maxRedirects: Int64, cacheMode: RawCacheMode, reportProgress: Bool, wantTimings: Bool, uploadContentLength: Int64, pinnedSpkiOverride: String, cancelTokenId: Int64) {
    self.connectTimeoutMs = connectTimeoutMs
    self.requestTimeoutMs = requestTimeoutMs
    self.followRedirects = followRedirects
    self.maxRedirects = maxRedirects
    self.cacheMode = cacheMode
    self.reportProgress = reportProgress
    self.wantTimings = wantTimings
    self.uploadContentLength = uploadContentLength
    self.pinnedSpkiOverride = pinnedSpkiOverride
    self.cancelTokenId = cancelTokenId
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawRequestOptions {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawRequestOptions {
    return RawRequestOptions(
      connectTimeoutMs: r.readInt(),
      requestTimeoutMs: r.readInt(),
      followRedirects: r.readInt(),
      maxRedirects: r.readInt(),
      cacheMode: RawCacheMode(rawValue: r.readInt())!,
      reportProgress: r.readBool(),
      wantTimings: r.readBool(),
      uploadContentLength: r.readInt(),
      pinnedSpkiOverride: r.readString(),
      cancelTokenId: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(connectTimeoutMs)
    writer.writeInt(requestTimeoutMs)
    writer.writeInt(followRedirects)
    writer.writeInt(maxRedirects)
    writer.writeInt(cacheMode.rawValue)
    writer.writeBool(reportProgress)
    writer.writeBool(wantTimings)
    writer.writeInt(uploadContentLength)
    writer.writeString(pinnedSpkiOverride)
    writer.writeInt(cancelTokenId)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawRequest: NitroEncodable {
  public var requestId: Int64
  public var method: RawMethod
  public var customMethod: String
  public var url: String
  public var headers: [RawHeader]
  public var bodyKind: RawBodyKind
  public var bodyFilePath: String
  public var responseFilePath: String
  public var options: RawRequestOptions

  public init(requestId: Int64, method: RawMethod, customMethod: String, url: String, headers: [RawHeader], bodyKind: RawBodyKind, bodyFilePath: String, responseFilePath: String, options: RawRequestOptions) {
    self.requestId = requestId
    self.method = method
    self.customMethod = customMethod
    self.url = url
    self.headers = headers
    self.bodyKind = bodyKind
    self.bodyFilePath = bodyFilePath
    self.responseFilePath = responseFilePath
    self.options = options
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawRequest {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawRequest {
    return RawRequest(
      requestId: r.readInt(),
      method: RawMethod(rawValue: r.readInt())!,
      customMethod: r.readString(),
      url: r.readString(),
      headers: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) },
      bodyKind: RawBodyKind(rawValue: r.readInt())!,
      bodyFilePath: r.readString(),
      responseFilePath: r.readString(),
      options: RawRequestOptions.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(requestId)
    writer.writeInt(method.rawValue)
    writer.writeString(customMethod)
    writer.writeString(url)
    writer.writeInt32(Int32(headers.count))
    for e in headers { e.writeFields(writer) }
    writer.writeInt(bodyKind.rawValue)
    writer.writeString(bodyFilePath)
    writer.writeString(responseFilePath)
    options.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawTimings: NitroEncodable {
  public var queueMs: Double
  public var dnsMs: Double
  public var connectMs: Double
  public var tlsMs: Double
  public var firstByteMs: Double
  public var redirectMs: Double
  public var totalMs: Double

  public init(queueMs: Double, dnsMs: Double, connectMs: Double, tlsMs: Double, firstByteMs: Double, redirectMs: Double, totalMs: Double) {
    self.queueMs = queueMs
    self.dnsMs = dnsMs
    self.connectMs = connectMs
    self.tlsMs = tlsMs
    self.firstByteMs = firstByteMs
    self.redirectMs = redirectMs
    self.totalMs = totalMs
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawTimings {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawTimings {
    return RawTimings(
      queueMs: r.readDouble(),
      dnsMs: r.readDouble(),
      connectMs: r.readDouble(),
      tlsMs: r.readDouble(),
      firstByteMs: r.readDouble(),
      redirectMs: r.readDouble(),
      totalMs: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeDouble(queueMs)
    writer.writeDouble(dnsMs)
    writer.writeDouble(connectMs)
    writer.writeDouble(tlsMs)
    writer.writeDouble(firstByteMs)
    writer.writeDouble(redirectMs)
    writer.writeDouble(totalMs)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawResponse: NitroEncodable {
  public var requestId: Int64
  public var errorKind: RawErrorKind
  public var errorMessage: String
  public var engineErrorCode: Int64
  public var statusCode: Int64
  public var reasonPhrase: String
  public var version: RawHttpVersion
  public var finalUrl: String
  public var redirectCount: Int64
  public var headers: [RawHeader]
  public var body: Data
  public var fromCache: Bool
  public var revalidated: Bool
  public var primaryIp: String
  public var primaryPort: Int64
  public var timings: RawTimings

  public init(requestId: Int64, errorKind: RawErrorKind, errorMessage: String, engineErrorCode: Int64, statusCode: Int64, reasonPhrase: String, version: RawHttpVersion, finalUrl: String, redirectCount: Int64, headers: [RawHeader], body: Data, fromCache: Bool, revalidated: Bool, primaryIp: String, primaryPort: Int64, timings: RawTimings) {
    self.requestId = requestId
    self.errorKind = errorKind
    self.errorMessage = errorMessage
    self.engineErrorCode = engineErrorCode
    self.statusCode = statusCode
    self.reasonPhrase = reasonPhrase
    self.version = version
    self.finalUrl = finalUrl
    self.redirectCount = redirectCount
    self.headers = headers
    self.body = body
    self.fromCache = fromCache
    self.revalidated = revalidated
    self.primaryIp = primaryIp
    self.primaryPort = primaryPort
    self.timings = timings
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawResponse {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawResponse {
    return RawResponse(
      requestId: r.readInt(),
      errorKind: RawErrorKind(rawValue: r.readInt())!,
      errorMessage: r.readString(),
      engineErrorCode: r.readInt(),
      statusCode: r.readInt(),
      reasonPhrase: r.readString(),
      version: RawHttpVersion(rawValue: r.readInt())!,
      finalUrl: r.readString(),
      redirectCount: r.readInt(),
      headers: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) },
      body: r.readBlob(),
      fromCache: r.readBool(),
      revalidated: r.readBool(),
      primaryIp: r.readString(),
      primaryPort: r.readInt(),
      timings: RawTimings.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(requestId)
    writer.writeInt(errorKind.rawValue)
    writer.writeString(errorMessage)
    writer.writeInt(engineErrorCode)
    writer.writeInt(statusCode)
    writer.writeString(reasonPhrase)
    writer.writeInt(version.rawValue)
    writer.writeString(finalUrl)
    writer.writeInt(redirectCount)
    writer.writeInt32(Int32(headers.count))
    for e in headers { e.writeFields(writer) }
    writer.writeBlob(body)
    writer.writeBool(fromCache)
    writer.writeBool(revalidated)
    writer.writeString(primaryIp)
    writer.writeInt(primaryPort)
    timings.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawResponseHead: NitroEncodable {
  public var requestId: Int64
  public var errorKind: RawErrorKind
  public var errorMessage: String
  public var engineErrorCode: Int64
  public var statusCode: Int64
  public var reasonPhrase: String
  public var version: RawHttpVersion
  public var finalUrl: String
  public var redirectCount: Int64
  public var headers: [RawHeader]
  public var fromCache: Bool
  public var contentLength: Int64
  public var primaryIp: String
  public var primaryPort: Int64
  public var timings: RawTimings

  public init(requestId: Int64, errorKind: RawErrorKind, errorMessage: String, engineErrorCode: Int64, statusCode: Int64, reasonPhrase: String, version: RawHttpVersion, finalUrl: String, redirectCount: Int64, headers: [RawHeader], fromCache: Bool, contentLength: Int64, primaryIp: String, primaryPort: Int64, timings: RawTimings) {
    self.requestId = requestId
    self.errorKind = errorKind
    self.errorMessage = errorMessage
    self.engineErrorCode = engineErrorCode
    self.statusCode = statusCode
    self.reasonPhrase = reasonPhrase
    self.version = version
    self.finalUrl = finalUrl
    self.redirectCount = redirectCount
    self.headers = headers
    self.fromCache = fromCache
    self.contentLength = contentLength
    self.primaryIp = primaryIp
    self.primaryPort = primaryPort
    self.timings = timings
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawResponseHead {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawResponseHead {
    return RawResponseHead(
      requestId: r.readInt(),
      errorKind: RawErrorKind(rawValue: r.readInt())!,
      errorMessage: r.readString(),
      engineErrorCode: r.readInt(),
      statusCode: r.readInt(),
      reasonPhrase: r.readString(),
      version: RawHttpVersion(rawValue: r.readInt())!,
      finalUrl: r.readString(),
      redirectCount: r.readInt(),
      headers: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) },
      fromCache: r.readBool(),
      contentLength: r.readInt(),
      primaryIp: r.readString(),
      primaryPort: r.readInt(),
      timings: RawTimings.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(requestId)
    writer.writeInt(errorKind.rawValue)
    writer.writeString(errorMessage)
    writer.writeInt(engineErrorCode)
    writer.writeInt(statusCode)
    writer.writeString(reasonPhrase)
    writer.writeInt(version.rawValue)
    writer.writeString(finalUrl)
    writer.writeInt(redirectCount)
    writer.writeInt32(Int32(headers.count))
    for e in headers { e.writeFields(writer) }
    writer.writeBool(fromCache)
    writer.writeInt(contentLength)
    writer.writeString(primaryIp)
    writer.writeInt(primaryPort)
    timings.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawEvent: NitroEncodable {
  public var requestId: Int64
  public var kind: RawEventKind
  public var a: Int64
  public var b: Int64
  public var message: String

  public init(requestId: Int64, kind: RawEventKind, a: Int64, b: Int64, message: String) {
    self.requestId = requestId
    self.kind = kind
    self.a = a
    self.b = b
    self.message = message
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawEvent {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawEvent {
    return RawEvent(
      requestId: r.readInt(),
      kind: RawEventKind(rawValue: r.readInt())!,
      a: r.readInt(),
      b: r.readInt(),
      message: r.readString()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(requestId)
    writer.writeInt(kind.rawValue)
    writer.writeInt(a)
    writer.writeInt(b)
    writer.writeString(message)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawCookie: NitroEncodable {
  public var name: String
  public var value: String
  public var domain: String
  public var path: String
  public var expiresEpochMs: Int64
  public var secure: Bool
  public var httpOnly: Bool

  public init(name: String, value: String, domain: String, path: String, expiresEpochMs: Int64, secure: Bool, httpOnly: Bool) {
    self.name = name
    self.value = value
    self.domain = domain
    self.path = path
    self.expiresEpochMs = expiresEpochMs
    self.secure = secure
    self.httpOnly = httpOnly
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawCookie {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawCookie {
    return RawCookie(
      name: r.readString(),
      value: r.readString(),
      domain: r.readString(),
      path: r.readString(),
      expiresEpochMs: r.readInt(),
      secure: r.readBool(),
      httpOnly: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(name)
    writer.writeString(value)
    writer.writeString(domain)
    writer.writeString(path)
    writer.writeInt(expiresEpochMs)
    writer.writeBool(secure)
    writer.writeBool(httpOnly)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawCacheConfig: NitroEncodable {
  public var enabled: Bool
  public var directory: String
  public var maxSizeBytes: Int64
  public var maxEntryBytes: Int64

  public init(enabled: Bool, directory: String, maxSizeBytes: Int64, maxEntryBytes: Int64) {
    self.enabled = enabled
    self.directory = directory
    self.maxSizeBytes = maxSizeBytes
    self.maxEntryBytes = maxEntryBytes
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawCacheConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawCacheConfig {
    return RawCacheConfig(
      enabled: r.readBool(),
      directory: r.readString(),
      maxSizeBytes: r.readInt(),
      maxEntryBytes: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(enabled)
    writer.writeString(directory)
    writer.writeInt(maxSizeBytes)
    writer.writeInt(maxEntryBytes)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawCacheStats: NitroEncodable {
  public var entryCount: Int64
  public var sizeBytes: Int64
  public var hitCount: Int64
  public var missCount: Int64
  public var revalidationCount: Int64
  public var evictionCount: Int64

  public init(entryCount: Int64, sizeBytes: Int64, hitCount: Int64, missCount: Int64, revalidationCount: Int64, evictionCount: Int64) {
    self.entryCount = entryCount
    self.sizeBytes = sizeBytes
    self.hitCount = hitCount
    self.missCount = missCount
    self.revalidationCount = revalidationCount
    self.evictionCount = evictionCount
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawCacheStats {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawCacheStats {
    return RawCacheStats(
      entryCount: r.readInt(),
      sizeBytes: r.readInt(),
      hitCount: r.readInt(),
      missCount: r.readInt(),
      revalidationCount: r.readInt(),
      evictionCount: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(entryCount)
    writer.writeInt(sizeBytes)
    writer.writeInt(hitCount)
    writer.writeInt(missCount)
    writer.writeInt(revalidationCount)
    writer.writeInt(evictionCount)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawWsConfig: NitroEncodable {
  public var socketId: Int64
  public var url: String
  public var protocols: [String]
  public var headers: [RawHeader]
  public var pingIntervalMs: Int64
  public var maxFrameBytes: Int64
  public var connectTimeoutMs: Int64
  public var tls: RawTlsConfig

  public init(socketId: Int64, url: String, protocols: [String], headers: [RawHeader], pingIntervalMs: Int64, maxFrameBytes: Int64, connectTimeoutMs: Int64, tls: RawTlsConfig) {
    self.socketId = socketId
    self.url = url
    self.protocols = protocols
    self.headers = headers
    self.pingIntervalMs = pingIntervalMs
    self.maxFrameBytes = maxFrameBytes
    self.connectTimeoutMs = connectTimeoutMs
    self.tls = tls
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawWsConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawWsConfig {
    return RawWsConfig(
      socketId: r.readInt(),
      url: r.readString(),
      protocols: (0..<Int(r.readInt32())).map { _ in r.readString() },
      headers: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) },
      pingIntervalMs: r.readInt(),
      maxFrameBytes: r.readInt(),
      connectTimeoutMs: r.readInt(),
      tls: RawTlsConfig.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(socketId)
    writer.writeString(url)
    writer.writeInt32(Int32(protocols.count))
    for e in protocols { writer.writeString(e) }
    writer.writeInt32(Int32(headers.count))
    for e in headers { e.writeFields(writer) }
    writer.writeInt(pingIntervalMs)
    writer.writeInt(maxFrameBytes)
    writer.writeInt(connectTimeoutMs)
    tls.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct RawWsHandshake: NitroEncodable {
  public var socketId: Int64
  public var errorKind: RawErrorKind
  public var errorMessage: String
  public var engineErrorCode: Int64
  public var statusCode: Int64
  public var negotiatedProtocol: String
  public var responseHeaders: [RawHeader]

  public init(socketId: Int64, errorKind: RawErrorKind, errorMessage: String, engineErrorCode: Int64, statusCode: Int64, negotiatedProtocol: String, responseHeaders: [RawHeader]) {
    self.socketId = socketId
    self.errorKind = errorKind
    self.errorMessage = errorMessage
    self.engineErrorCode = engineErrorCode
    self.statusCode = statusCode
    self.negotiatedProtocol = negotiatedProtocol
    self.responseHeaders = responseHeaders
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> RawWsHandshake {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> RawWsHandshake {
    return RawWsHandshake(
      socketId: r.readInt(),
      errorKind: RawErrorKind(rawValue: r.readInt())!,
      errorMessage: r.readString(),
      engineErrorCode: r.readInt(),
      statusCode: r.readInt(),
      negotiatedProtocol: r.readString(),
      responseHeaders: (0..<Int(r.readInt32())).map { _ in RawHeader.fromReader(r) }
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(socketId)
    writer.writeInt(errorKind.rawValue)
    writer.writeString(errorMessage)
    writer.writeInt(engineErrorCode)
    writer.writeInt(statusCode)
    writer.writeString(negotiatedProtocol)
    writer.writeInt32(Int32(responseHeaders.count))
    for e in responseHeaders { e.writeFields(writer) }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableInt: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableInt {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableInt {
    return NitroNullableInt(
      hasValue: r.readBool(),
      value: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Int64? { hasValue ? value : nil }
  public static func fromNullable(_ v: Int64?) -> NitroNullableInt {
    return NitroNullableInt(hasValue: v != nil, value: v ?? 0)
  }
}

public struct NitroNullableDouble: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableDouble {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableDouble {
    return NitroNullableDouble(
      hasValue: r.readBool(),
      value: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Double? { hasValue ? value : nil }
  public static func fromNullable(_ v: Double?) -> NitroNullableDouble {
    return NitroNullableDouble(hasValue: v != nil, value: v ?? 0.0)
  }
}

public struct NitroNullableBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableBool {
    return NitroNullableBool(
      hasValue: r.readBool(),
      value: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Bool? { hasValue ? value : nil }
  public static func fromNullable(_ v: Bool?) -> NitroNullableBool {
    return NitroNullableBool(hasValue: v != nil, value: v ?? false)
  }
}

public struct NitroOptInt64: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptInt64 {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptInt64 {
    return NitroOptInt64(
      hasValue: r.readBool(),
      value: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroOptFloat64: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptFloat64 {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptFloat64 {
    return NitroOptFloat64(
      hasValue: r.readBool(),
      value: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroOptBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptBool {
    return NitroOptBool(
      hasValue: r.readBool(),
      value: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public class NitroRecordWriter {
  public var bytes: [UInt8] = []
  public init() {}
  public func writeInt(_ v: Int64) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeInt32(_ v: Int32) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeDouble(_ v: Double) {
      var val = v.bitPattern.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeBool(_ v: Bool) {
      bytes.append(v ? 1 : 0)
  }
  public func writeString(_ v: String) {
      let utf8 = Array(v.utf8)
      writeInt32(Int32(utf8.count))
      bytes.append(contentsOf: utf8)
  }
  public func writeNullTag(_ isNull: Bool) {
      bytes.append(isNull ? 0 : 1)
  }
  public func writeBlob(_ v: Data) {
      writeInt32(Int32(v.count))
      bytes.append(contentsOf: Array(v))
  }
  public func toNative() -> UnsafeMutablePointer<UInt8>? {
      let total = 4 + bytes.count
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
      var length = Int32(bytes.count).littleEndian
      _ = memcpy(ptr, &length, 4)
      if bytes.count > 0 {
          _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
      }
      return ptr
  }
  public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items { writeItem(w, item) }
      return w.toNative()
  }
  /// Encodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordReader.decodeNullableList / Dart RecordReader.decodeNullableList.
  public static func encodeNullableList<T>(_ items: [T?], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items {
          w.writeBool(item != nil)
          if let v = item { writeItem(w, v) }
      }
      return w.toNative()
  }
  /// Encodes a list with a per-item byte-offset table for O(1) random access.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
  public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      var blobs: [[UInt8]] = []
      for item in items {
          let w = NitroRecordWriter()
          writeItem(w, item)
          blobs.append(w.bytes)
      }
      var pos = 4 + 8 * blobs.count
      var offsets: [Int64] = []
      for blob in blobs {
          offsets.append(Int64(pos))
          pos += blob.count
      }
      let w = NitroRecordWriter()
      w.writeInt32(Int32(blobs.count))
      for off in offsets { w.writeInt(off) }
      for blob in blobs { w.bytes.append(contentsOf: blob) }
      return w.toNative()
  }
}

public class NitroRecordReader {
  public let bytes: UnsafeMutablePointer<UInt8>
  public var pos: Int = 0
  public init(ptr: UnsafeMutablePointer<UInt8>) {
      self.bytes = ptr.advanced(by: 4)
  }
  public init(payload: UnsafeMutablePointer<UInt8>) {
      self.bytes = payload
  }
  public func readInt() -> Int64 {
      var v: Int64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Int64(littleEndian: v)
  }
  public func readInt32() -> Int32 {
      var v: Int32 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 4)
      pos += 4
      return Int32(littleEndian: v)
  }
  public func readDouble() -> Double {
      var v: UInt64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Double(bitPattern: UInt64(littleEndian: v))
  }
  public func readBool() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v != 0
  }
  public func readString() -> String {
      let len = Int(readInt32())
      guard len > 0 else { return "" }
      let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
      pos += len
      return s
  }
  public func readNullTag() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v == 0
  }
  public func readBlob() -> Data {
      let len = Int(readInt32())
      let data = Data(bytes: bytes.advanced(by: pos), count: len)
      pos += len
      return data
  }
  public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
      let len = Int(readInt32())
      if (len == 0) { return nil }
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
      ptr.initialize(from: bytes.advanced(by: pos), count: len)
      pos += len
      return ptr
  }
  public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
  /// Decodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordWriter.encodeNullableList / Dart RecordWriter.encodeNullableList.
  public static func decodeNullableList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T?] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T?] = []
      for _ in 0..<count {
          let hasValue = r.readBool()
          items.append(hasValue ? readItem(r) : nil)
      }
      return items
  }
  /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// The offset table is skipped; items are read sequentially after it.
  public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      r.pos += Int(count) * 8  // skip Int64 offset table
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
}

/**
 * Protocol for the NitroHttpNative module (NativeImpl.cpp).
 * Conform to this in your Swift/ObjC++ source code if you want
 * to delegate from the C++ HybridObject to a Swift implementation.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroHttpNativeProtocol: AnyObject {
    func engineVersion() -> String
    func supportsHttp3() -> Bool
    func supportsWebSockets() -> Bool
    func supportsBrotli() -> Bool
    func supportsZstd() -> Bool
    func resetNative() -> Void
    func configureClient(config: RawClientConfig) -> Void
    func sendBuffered(request: RawRequest, body: Data) async throws -> RawResponse
    func sendBufferedCoalesced(callId: Int64, request: RawRequest, body: Data, dartPort: Int64) -> Void
    func releaseRecord(address: Int64) -> Void
    func startStreamed(request: RawRequest, body: Data) async throws -> RawResponseHead
    func cancel(requestId: Int64) -> Void
    func cancelAll() -> Void
    func cancelToken(tokenId: Int64, reason: String) -> Void
    func releaseCancelToken(tokenId: Int64) -> Void
    func grantCredit(requestId: Int64, chunkCount: Int64, ackedChunks: Int64) -> Void
    func feedUploadChunk(requestId: Int64, chunk: Data) -> Int64
    func finishUpload(requestId: Int64) -> Void
    func failUpload(requestId: Int64, message: String) -> Void
    func getCookies(url: String) -> [RawCookie]
    func setCookie(cookie: RawCookie) -> Void
    func clearCookies() -> Void
    func flushCookies() -> Void
    func configureCache(config: RawCacheConfig) -> Void
    func prefetch(request: RawRequest) async throws -> RawResponse
    func clearCache() -> Void
    func cacheStats() -> RawCacheStats
    func wsConnect(config: RawWsConfig) async throws -> RawWsHandshake
    func wsSend(opcode: Int64, payload: Data) -> Int64
    func wsClose(code: Int64, reason: String) -> Void
    func wsGrantCredit(frameCount: Int64, ackedFrames: Int64) -> Void
    var chunks: AnyPublisher<RawChunk, Never> { get }
    var events: AnyPublisher<RawEvent, Never> { get }
    var wsFrames: AnyPublisher<RawWsFrame, Never> { get }
}

public class NitroHttpNativeRegistry {
    public static var impl: HybridNitroHttpNativeProtocol?

    public static func register(_ impl: HybridNitroHttpNativeProtocol) {
        NitroHttpNativeRegistry.impl = impl
    }

    // Stream: chunks cancellables keyed by dartPort
    public static var _chunksCancellables = [Int64: AnyCancellable]()

    // Stream: events cancellables keyed by dartPort
    public static var _eventsCancellables = [Int64: AnyCancellable]()

    // Stream: wsFrames cancellables keyed by dartPort
    public static var _wsFramesCancellables = [Int64: AnyCancellable]()
}

// NOTE: @_cdecl bridge stubs are NOT generated for NativeImpl.cpp modules.
// The .bridge.g.mm C++ shim calls nitro_http_xxx() C functions directly.
